; Vista locales
InitLocales:
LocaleList=Afrikaans|Albanian|Alsatian (France)|Amharic (Ethiopia)|Arabic (Algeria)|Arabic (Bahrain)|Arabic (Egypt)|Arabic (Iraq)|Arabic (Jordan)|Arabic (Kuwait)|Arabic (Lebanon)|Arabic (Libya)|Arabic (Morocco)|Arabic (Oman)|Arabic (Qatar)|Arabic (Saudi Arabia)|Arabic (Syria)|Arabic (Tunisia)|Arabic (U.A.E.)|Arabic (Yemen)|Armenian|Assamese (India)|Azeri (Cyrillic)|Azeri (Latin)|Bashkir (Russia)|Basque|Belarusian|Bengali (Bangladesh)|Bengali (India)|Bosnian (Cyrillic, Bosnia and Herzegovina)|Bosnian (Latin, Bosnia and Herzegovina)|Breton (France)|Bulgarian|Catalan|Chinese (Hong Kong)|Chinese (Macao)|Chinese (PRC)|Chinese (Simplified)|Chinese (Singapore)|Chinese (Taiwan)|Chinese (Traditional)|Corsican (France)|Croatian|Croatian (Latin, Bosnia and Herzegovina)|Czech|Danish|Dari (Afghanistan)|Divehi|Dutch (Belgium)|Dutch (Standard)|English (Australia)|English (Belize)|English (Canada)|English (Caribbean)|English (India)|English (Ireland)|English (Jamaica)|English (Malaysia)|English (New Zealand)|English (Philippines)|English (Singapore)|English (South Africa)|English (Trinidad and Tobago)|English (United Kingdom)|English (United States)|English (Zimbabwe)|Estonian|Faroese|Farsi|Filipino (Philippines)|Finnish|French (Belgian)|French (Canadia)|French (Standard)|French (Luxembourg)|French (Monaco)|French (Swiss)|Frisian (Netherlands)|Galician|Georgian|German (Austrian)|German (Standard)|German (Liechtenstein)|German (Luxembourg)|German (Swiss)|Greek|Greenlandic (Greenland)|Gujarati|Hausa (Latin, Nigeria)|Hebrew|Hindi|Hungarian|Icelandic|Igbo (Nigeria)|Indonesian|Inuktitut (Latin, Canada)|Inuktitut (Syllabics, Canada)|Irish (Ireland)|isiXhosa (South Africa)|isiZulu (South Africa)|Italian (Standard)|Italian (Swiss)|Japanese|Kannada|Kazakh|Khmer (Cambodia)|K'iche (Guatemala)|Kinyarwanda (Rwanda)|Konkani|Korean|Kyrgyz|Lao (Lao P.D.R.)|Latvian|Lithuanian|Lower Sorbian (Germany)|Luxembourgish (Luxembourg)|Macedonian|Malay (Brunei Darussalam)|Malay (Malaysia)|Malayalam (India)|Maltese (Malta)|Maori (New Zealand)|Mapudungun (Chile)|Marathi|Mohawk (Mohawk)|Mongolian (Cyrillic, Mongolia)|Mongolian (Traditional Mongolian, PRC)|Nepali (Nepal)|Norwegian (Bokmal)|Norwegian (Nynorsk)|Occitan (France)|Oriya (India)|Pashto (Afghanistan)|Persian|Polish|Portuguese (Brazilian)|Portuguese (Standard)|Punjabi|Quechua (Bolivia)|Quechua (Ecuador)|Quechua (Peru)|Romanian|Romansh (Switzerland)|Russian|Sami, Inari (Finland)|Sami, Lule (Norway)|Sami, Lule (Sweden)|Sami, Northern (Finland)|Sami, Northern (Norway)|Sami, Northern (Sweden)|Sami, Skolt (Finland)|Sami, Southern (Norway)|Sami, Southern (Sweden)|Sanskrit|Serbian (Cyrillic, Bosnia and Herzegovina)|Serbian (Cyrillic, Serbia)|Serbian (Latin, Bosnia and Herzegovina)|Serbian (Latin, Serbia)|Sesotho sa Leboa (South Africa)|Setswana (South Africa)|Sinhala (Sri Lanka)|Slovak|Slovenian|Spanish (Argentina)|Spanish (Bolivia)|Spanish (Chile)|Spanish (Colombia)|Spanish (Costa Rica)|Spanish (Dominican Republic)|Spanish (Ecuador)|Spanish (El Salvador)|Spanish (Guatemala)|Spanish (Honduras)|Spanish (Mexican)|Spanish (Nicaragua)|Spanish (Panama)|Spanish (Paraguay)|Spanish (Peru)|Spanish (Puerto Rico)|Spanish (Spain)|Spanish (United States)|Spanish (Uruguay)|Spanish (Venezuela)|Swahili|Swedish (Finland)|Swedish|Syriac|Tajik (Cyrillic, Tajikistan)|Tamazight (Latin, Algeria)|Tamil|Tatar|Telugu|Thai|Tibetan (PRC)|Turkish|Turkmen (Turkmenistan)|Uighur (PRC)|Ukrainian|Upper Sorbian (Germany)|Urdu|Uzbek (Cyrillic)|Uzbek (Latin)|Vietnamese|Welsh (United Kingdom)|Wolof (Senegal)|Yakut (Russia)|Yi (PRC)|Yoruba (Nigeria)

; Win2000 locales
AltLocaleList=Afrikaans|Albanian|Arabic (Saudi Arabia)|Arabic (Iraq)|Arabic (Egypt)|Arabic (Libya)|Arabic (Algeria)|Arabic (Morocco)|Arabic (Tunisia)|Arabic (Oman)|Arabic (Yemen)|Arabic (Syria)|Arabic (Jordan)|Arabic (Lebanon)|Arabic (Kuwait)|Arabic (UAE)|Arabic (Bahrain)|Arabic (Qatar)|Armenian|Azeri (Latin)|Azeri (Cyrillic)|Basque|Belarusian|Bulgarian|Catalan|Chinese (Taiwan)|Chinese (PRC)|Chinese (Hong Kong)|Chinese (Singapore)|Chinese (Macau)|Croatian|Czech|Danish|Dutch (Standard)|Dutch (Belgian)|English (United States)|English (United Kingdom)|English (Australian)|English (Canadian)|English (New Zealand)|English (Irish)|English (South Africa)|English (Jamaica)|English (Caribbean)|English (Belize)|English (Trinidad)|English (Zimbabwe)|English (Philippines)|Estonian|Faeroese|Farsi|Finnish|French (Standard)|French (Belgian)|French (Canadia)|French (Swiss)|French (Luxembourg)|French (Monaco)|Georgian|German (Standard)|German (Swiss)|German (Austrian)|German (Luxembourg)|German (Liechtenstein)|Greek|Hebrew|Hindi|Hungarian|Icelandic|Indonesian|Italian (Standard)|Italian (Swiss)|Japanese|Kazakh|Konkani|Korean|Latvian|Lithuanian|Macedonian|Malay (Malaysia)|Malay (Brunei Darussalam)|Marathi|Norwegian (Bokmal)|Norwegian (Nynorsk)|Polish|Portuguese (Brazilian)|Portuguese (Standard)|Romanian|Russian|Sanskrit|Serbian (Latin)|Serbian (Cyrillic)|Slovak|Slovenian|Spanish (Spain)|Spanish (Mexican)|Spanish (Guatemala)|Spanish (Costa Rica)|Spanish (Panama)|Spanish (Dominican Republic)|Spanish (Venezuela)|Spanish (Colombia)|Spanish (Peru)|Spanish (Argentina)|Spanish (Ecuador)|Spanish (Chile)|Spanish (Uruguay)|Spanish (Paraguay)|Spanish (Bolivia)|Spanish (El Salvador)|Spanish (Honduras)|Spanish (Nicaragua)|Spanish (Puerto Rico)|Swahili|Swedish|Swedish (Finland)|Tamil|Tatar|Thai|Turkish|Ukrainian|Urdu|Uzbek (Latin)|Uzbek (Cyrillic)|Vietnamese
return

ConvertCodeToName(Lang)
{
If Lang=0436
	LangName=Afrikaans
If Lang=041C
	LangName=Albanian
If Lang=0484
	LangName=Alsatian (France)
If Lang=045E
	LangName=Amharic (Ethiopia)
If Lang=1401
	LangName=Arabic (Algeria)
If Lang=3C01
	LangName=Arabic (Bahrain)
If Lang=0C01
	LangName=Arabic (Egypt)
If Lang=0801
	LangName=Arabic (Iraq)
If Lang=2C01
	LangName=Arabic (Jordan)
If Lang=3401
	LangName=Arabic (Kuwait)
If Lang=3001
	LangName=Arabic (Lebanon)
If Lang=1001
	LangName=Arabic (Libya)
If Lang=1801
	LangName=Arabic (Morocco)
If Lang=2001
	LangName=Arabic (Oman)
If Lang=4001
	LangName=Arabic (Qatar)
If Lang=0401
	LangName=Arabic (Saudi Arabia)
If Lang=2801
	LangName=Arabic (Syria)
If Lang=1C01
	LangName=Arabic (Tunisia)
If Lang=3801
	LangName=Arabic (U.A.E.)
If Lang=2401
	LangName=Arabic (Yemen)
If Lang=042B
	LangName=Armenian
If Lang=044D
	LangName=Assamese (India)
If Lang=082C
	LangName=Azeri (Cyrillic)
If Lang=042C
	LangName=Azeri (Latin)
If Lang=046D
	LangName=Bashkir (Russia)
If Lang=042D
	LangName=Basque
If Lang=0423
	LangName=Belarusian
If Lang=0845
	LangName=Bengali (Bangladesh)
If Lang=0445
	LangName=Bengali (India)
If Lang=201A
	LangName=Bosnian (Cyrillic, Bosnia and Herzegovina)
If Lang=141A
	LangName=Bosnian (Latin, Bosnia and Herzegovina)
If Lang=047E
	LangName=Breton (France)
If Lang=0402
	LangName=Bulgarian
If Lang=0403
	LangName=Catalan
If Lang=0C04
	LangName=Chinese (Hong Kong)
If Lang=1404
	LangName=Chinese (Macao)
If Lang=0804
	LangName=Chinese (PRC)
If Lang=0004
	LangName=Chinese (Simplified)
If Lang=1004
	LangName=Chinese (Singapore)
If Lang=0404
	LangName=Chinese (Taiwan)
If Lang=7C04
	LangName=Chinese (Traditional)
If Lang=0483
	LangName=Corsican (France)
If Lang=041A
	LangName=Croatian
If Lang=101A
	LangName=Croatian (Latin, Bosnia and Herzegovina)
If Lang=0405
	LangName=Czech
If Lang=0406
	LangName=Danish
If Lang=048C
	LangName=Dari (Afghanistan)
If Lang=0465
	LangName=Divehi
If Lang=0813
	LangName=Dutch (Belgium)
If Lang=0413
	LangName=Dutch (Standard)
If Lang=0C09
	LangName=English (Australia)
If Lang=2809
	LangName=English (Belize)
If Lang=1009
	LangName=English (Canada)
If Lang=2409
	LangName=English (Caribbean)
If Lang=4009
	LangName=English (India)
If Lang=1809
	LangName=English (Ireland)
If Lang=2009
	LangName=English (Jamaica)
If Lang=4409
	LangName=English (Malaysia)
If Lang=1409
	LangName=English (New Zealand)
If Lang=3409
	LangName=English (Philippines)
If Lang=4809
	LangName=English (Singapore)
If Lang=1C09
	LangName=English (South Africa)
If Lang=2C09
	LangName=English (Trinidad and Tobago)
If Lang=0809
	LangName=English (United Kingdom)
If Lang=0409
	LangName=English (United States)
If Lang=3009
	LangName=English (Zimbabwe)
If Lang=0425
	LangName=Estonian
If Lang=0438
	LangName=Faroese
If Lang=0429
	LangName=Farsi
If Lang=0464
	LangName=Filipino (Philippines)
If Lang=040B
	LangName=Finnish
If Lang=080C
	LangName=French (Belgian)
If Lang=0C0C
	LangName=French (Canadia)
If Lang=040C
	LangName=French (Standard)
If Lang=140C
	LangName=French (Luxembourg)
If Lang=180C
	LangName=French (Monaco)
If Lang=100C
	LangName=French (Swiss)
If Lang=0462
	LangName=Frisian (Netherlands)
If Lang=0456
	LangName=Galician
If Lang=0437
	LangName=Georgian
If Lang=0C07
	LangName=German (Austrian)
If Lang=0407
	LangName=German (Standard)
If Lang=1407
	LangName=German (Liechtenstein)
If Lang=1007
	LangName=German (Luxembourg)
If Lang=0807
	LangName=German (Swiss)
If Lang=0408
	LangName=Greek
If Lang=046F
	LangName=Greenlandic (Greenland)
If Lang=0447
	LangName=Gujarati
If Lang=0468
	LangName=Hausa (Latin, Nigeria)
If Lang=040D
	LangName=Hebrew
If Lang=0439
	LangName=Hindi
If Lang=040E
	LangName=Hungarian
If Lang=040F
	LangName=Icelandic
If Lang=0470
	LangName=Igbo (Nigeria)
If Lang=0421
	LangName=Indonesian
If Lang=085D
	LangName=Inuktitut (Latin, Canada)
If Lang=045D
	LangName=Inuktitut (Syllabics, Canada)
If Lang=083C
	LangName=Irish (Ireland)
If Lang=0434
	LangName=isiXhosa (South Africa)
If Lang=0435
	LangName=isiZulu (South Africa)
If Lang=0410
	LangName=Italian (Standard)
If Lang=0810
	LangName=Italian (Swiss)
If Lang=0411
	LangName=Japanese
If Lang=044B
	LangName=Kannada
If Lang=043F
	LangName=Kazakh
If Lang=0453
	LangName=Khmer (Cambodia)
If Lang=0486
	LangName=K'iche (Guatemala)
If Lang=0487
	LangName=Kinyarwanda (Rwanda)
If Lang=0457
	LangName=Konkani
If Lang=0412
	LangName=Korean
If Lang=0440
	LangName=Kyrgyz
If Lang=0454
	LangName=Lao (Lao P.D.R.)
If Lang=0426
	LangName=Latvian
If Lang=0427
	LangName=Lithuanian
If Lang=082E
	LangName=Lower Sorbian (Germany)
If Lang=046E
	LangName=Luxembourgish (Luxembourg)
If Lang=042F
	LangName=Macedonian
If Lang=083E
	LangName=Malay (Brunei Darussalam)
If Lang=043E
	LangName=Malay (Malaysia)
If Lang=044C
	LangName=Malayalam (India)
If Lang=043A
	LangName=Maltese (Malta)
If Lang=0481
	LangName=Maori (New Zealand)
If Lang=047A
	LangName=Mapudungun (Chile)
If Lang=044E
	LangName=Marathi
If Lang=047C
	LangName=Mohawk (Mohawk)
If Lang=0450
	LangName=Mongolian (Cyrillic, Mongolia)
If Lang=0850
	LangName=Mongolian (Traditional Mongolian, PRC)
If Lang=0461
	LangName=Nepali (Nepal)
If Lang=0414
	LangName=Norwegian (Bokmal)
If Lang=0814
	LangName=Norwegian (Nynorsk)
If Lang=0482
	LangName=Occitan (France)
If Lang=0448
	LangName=Oriya (India)
If Lang=0463
	LangName=Pashto (Afghanistan)
If Lang=0429
	LangName=Persian
If Lang=0415
	LangName=Polish
If Lang=0416
	LangName=Portuguese (Brazilian)
If Lang=0816
	LangName=Portuguese (Standard)
If Lang=0446
	LangName=Punjabi
If Lang=046B
	LangName=Quechua (Bolivia)
If Lang=086B
	LangName=Quechua (Ecuador)
If Lang=0C6B
	LangName=Quechua (Peru)
If Lang=0418
	LangName=Romanian
If Lang=0417
	LangName=Romansh (Switzerland)
If Lang=0419
	LangName=Russian
If Lang=243B
	LangName=Sami, Inari (Finland)
If Lang=103B
	LangName=Sami, Lule (Norway)
If Lang=143B
	LangName=Sami, Lule (Sweden)
If Lang=0C3B
	LangName=Sami, Northern (Finland)
If Lang=043B
	LangName=Sami, Northern (Norway)
If Lang=083B
	LangName=Sami, Northern (Sweden)
If Lang=203B
	LangName=Sami, Skolt (Finland)
If Lang=183B
	LangName=Sami, Southern (Norway)
If Lang=1C3B
	LangName=Sami, Southern (Sweden)
If Lang=044F
	LangName=Sanskrit
If Lang=1C1A
	LangName=Serbian (Cyrillic, Bosnia and Herzegovina)
If Lang=0C1A
	LangName=Serbian (Cyrillic)
If Lang=181A
	LangName=Serbian (Latin, Bosnia and Herzegovina)
If Lang=081A
	LangName=Serbian (Latin)
If Lang=046C
	LangName=Sesotho sa Leboa (South Africa)
If Lang=0432
	LangName=Setswana (South Africa)
If Lang=045B
	LangName=Sinhala (Sri Lanka)
If Lang=041B
	LangName=Slovak
If Lang=0424
	LangName=Slovenian
If Lang=2C0A
	LangName=Spanish (Argentina)
If Lang=400A
	LangName=Spanish (Bolivia)
If Lang=340A
	LangName=Spanish (Chile)
If Lang=240A
	LangName=Spanish (Colombia)
If Lang=140A
	LangName=Spanish (Costa Rica)
If Lang=1C0A
	LangName=Spanish (Dominican Republic)
If Lang=300A
	LangName=Spanish (Ecuador)
If Lang=440A
	LangName=Spanish (El Salvador)
If Lang=100A
	LangName=Spanish (Guatemala)
If Lang=480A
	LangName=Spanish (Honduras)
If Lang=080A
	LangName=Spanish (Mexican)
If Lang=4C0A
	LangName=Spanish (Nicaragua)
If Lang=180A
	LangName=Spanish (Panama)
If Lang=3C0A
	LangName=Spanish (Paraguay)
If Lang=280A
	LangName=Spanish (Peru)
If Lang=500A
	LangName=Spanish (Puerto Rico)
If Lang=0C0A
	LangName=Spanish (Spain)
If Lang=540A
	LangName=Spanish (United States)
If Lang=380A
	LangName=Spanish (Uruguay)
If Lang=200A
	LangName=Spanish (Venezuela)
If Lang=0441
	LangName=Swahili
If Lang=081D
	LangName=Swedish (Finland)
If Lang=041D
	LangName=Swedish
If Lang=045A
	LangName=Syriac
If Lang=0428
	LangName=Tajik (Cyrillic, Tajikistan)
If Lang=085F
	LangName=Tamazight (Latin, Algeria)
If Lang=0449
	LangName=Tamil
If Lang=0444
	LangName=Tatar
If Lang=044A
	LangName=Telugu
If Lang=041E
	LangName=Thai
If Lang=0451
	LangName=Tibetan (PRC)
If Lang=041F
	LangName=Turkish
If Lang=0442
	LangName=Turkmen (Turkmenistan)
If Lang=0480
	LangName=Uighur (PRC)
If Lang=0422
	LangName=Ukrainian
If Lang=042E
	LangName=Upper Sorbian (Germany)
If Lang=0420
	LangName=Urdu
If Lang=0843
	LangName=Uzbek (Cyrillic)
If Lang=0443
	LangName=Uzbek (Latin)
If Lang=042A
	LangName=Vietnamese
If Lang=0452
	LangName=Welsh (United Kingdom)
If Lang=0488
	LangName=Wolof (Senegal)
If Lang=0485
	LangName=Yakut (Russia)
If Lang=0478
	LangName=Yi (PRC)
If Lang=046A
	LangName=Yoruba (Nigeria)
return LangName
}

ConvertNameToCode(LangName) {
If LangName=Afrikaans
	Lang=0436
If LangName=Albanian
	Lang=041C
If LangName=Alsatian (France)
	Lang=0484
If LangName=Amharic (Ethiopia)
	Lang=045E
If LangName=Arabic (Algeria)
	Lang=1401
If LangName=Arabic (Bahrain)
	Lang=3C01
If LangName=Arabic (Egypt)
	Lang=0C01
If LangName=Arabic (Iraq)
	Lang=0801
If LangName=Arabic (Jordan)
	Lang=2C01
If LangName=Arabic (Kuwait)
	Lang=3401
If LangName=Arabic (Lebanon)
	Lang=3001
If LangName=Arabic (Libya)
	Lang=1001
If LangName=Arabic (Morocco)
	Lang=1801
If LangName=Arabic (Oman)
	Lang=2001
If LangName=Arabic (Qatar)
	Lang=4001
If LangName=Arabic (Saudi Arabia)
	Lang=0401
If LangName=Arabic (Syria)
	Lang=2801
If LangName=Arabic (Tunisia)
	Lang=1C01
If LangName=Arabic (U.A.E.)
	Lang=3801
If LangName=Arabic (Yemen)
	Lang=2401
If LangName=Armenian
	Lang=042B
If LangName=Assamese (India)
	Lang=044D
If LangName=Azeri (Cyrillic)
	Lang=082C
If LangName=Azeri (Latin)
	Lang=042C
If LangName=Bashkir (Russia)
	Lang=046D
If LangName=Basque
	Lang=042D
If LangName=Belarusian
	Lang=0423
If LangName=Bengali (Bangladesh)
	Lang=0845
If LangName=Bengali (India)
	Lang=0445
If LangName=Bosnian (Cyrillic, Bosnia and Herzegovina)
	Lang=201A
If LangName=Bosnian (Latin, Bosnia and Herzegovina)
	Lang=141A
If LangName=Breton (France)
	Lang=047E
If LangName=Bulgarian
	Lang=0402
If LangName=Catalan
	Lang=0403
If LangName=Chinese (Hong Kong)
	Lang=0C04
If LangName=Chinese (Macao)
	Lang=1404
If LangName=Chinese (PRC)
	Lang=0804
If LangName=Chinese (Simplified)
	Lang=0004
If LangName=Chinese (Singapore)
	Lang=1004
If LangName=Chinese (Taiwan)
	Lang=0404
If LangName=Chinese (Traditional)
	Lang=7C04
If LangName=Corsican (France)
	Lang=0483
If LangName=Croatian
	Lang=041A
If LangName=Croatian (Latin, Bosnia and Herzegovina)
	Lang=101A
If LangName=Czech
	Lang=0405
If LangName=Danish
	Lang=0406
If LangName=Dari (Afghanistan)
	Lang=048C
If LangName=Divehi
	Lang=0465
If LangName=Dutch (Belgium)
	Lang=0813
If LangName=Dutch (Standard)
	Lang=0413
If LangName=English (Australia)
	Lang=0C09
If LangName=English (Belize)
	Lang=2809
If LangName=English (Canada)
	Lang=1009
If LangName=English (Caribbean)
	Lang=2409
If LangName=English (India)
	Lang=4009
If LangName=English (Ireland)
	Lang=1809
If LangName=English (Jamaica)
	Lang=2009
If LangName=English (Malaysia)
	Lang=4409
If LangName=English (New Zealand)
	Lang=1409
If LangName=English (Philippines)
	Lang=3409
If LangName=English (Singapore)
	Lang=4809
If LangName=English (South Africa)
	Lang=1C09
If LangName=English (Trinidad and Tobago)
	Lang=2C09
If LangName=English (United Kingdom)
	Lang=0809
If LangName=English (United States)
	Lang=0409
If LangName=English (Zimbabwe)
	Lang=3009
If LangName=Estonian
	Lang=0425
If LangName=Faroese
	Lang=0438
If LangName=Farsi
	Lang=0429
If LangName=Filipino (Philippines)
	Lang=0464
If LangName=Finnish
	Lang=040B
If LangName=French (Belgian)
	Lang=080C
If LangName=French (Canadia)
	Lang=0C0C
If LangName=French (Standard)
	Lang=040C
If LangName=French (Luxembourg)
	Lang=140C
If LangName=French (Monaco)
	Lang=180C
If LangName=French (Swiss)
	Lang=100C
If LangName=Frisian (Netherlands)
	Lang=0462
If LangName=Galician
	Lang=0456
If LangName=Georgian
	Lang=0437
If LangName=German (Austrian)
	Lang=0C07
If LangName=German (Standard)
	Lang=0407
If LangName=German (Liechtenstein)
	Lang=1407
If LangName=German (Luxembourg)
	Lang=1007
If LangName=German (Swiss)
	Lang=0807
If LangName=Greek
	Lang=0408
If LangName=Greenlandic (Greenland)
	Lang=046F
If LangName=Gujarati
	Lang=0447
If LangName=Hausa (Latin, Nigeria)
	Lang=0468
If LangName=Hebrew
	Lang=040D
If LangName=Hindi
	Lang=0439
If LangName=Hungarian
	Lang=040E
If LangName=Icelandic
	Lang=040F
If LangName=Igbo (Nigeria)
	Lang=0470
If LangName=Indonesian
	Lang=0421
If LangName=Inuktitut (Latin, Canada)
	Lang=085D
If LangName=Inuktitut (Syllabics, Canada)
	Lang=045D
If LangName=Irish (Ireland)
	Lang=083C
If LangName=isiXhosa (South Africa)
	Lang=0434
If LangName=isiZulu (South Africa)
	Lang=0435
If LangName=Italian (Standard)
	Lang=0410
If LangName=Italian (Swiss)
	Lang=0810
If LangName=Japanese
	Lang=0411
If LangName=Kannada
	Lang=044B
If LangName=Kazakh
	Lang=043F
If LangName=Khmer (Cambodia)
	Lang=0453
If LangName=K'iche (Guatemala)
	Lang=0486
If LangName=Kinyarwanda (Rwanda)
	Lang=0487
If LangName=Konkani
	Lang=0457
If LangName=Korean
	Lang=0412
If LangName=Kyrgyz
	Lang=0440
If LangName=Lao (Lao P.D.R.)
	Lang=0454
If LangName=Latvian
	Lang=0426
If LangName=Lithuanian
	Lang=0427
If LangName=Lower Sorbian (Germany)
	Lang=082E
If LangName=Luxembourgish (Luxembourg)
	Lang=046E
If LangName=Macedonian
	Lang=042F
If LangName=Malay (Brunei Darussalam)
	Lang=083E
If LangName=Malay (Malaysia)
	Lang=043E
If LangName=Malayalam (India)
	Lang=044C
If LangName=Maltese (Malta)
	Lang=043A
If LangName=Maori (New Zealand)
	Lang=0481
If LangName=Mapudungun (Chile)
	Lang=047A
If LangName=Marathi
	Lang=044E
If LangName=Mohawk (Mohawk)
	Lang=047C
If LangName=Mongolian (Cyrillic, Mongolia)
	Lang=0450
If LangName=Mongolian (Traditional Mongolian, PRC)
	Lang=0850
If LangName=Nepali (Nepal)
	Lang=0461
If LangName=Norwegian (Bokmal)
	Lang=0414
If LangName=Norwegian (Nynorsk)
	Lang=0814
If LangName=Occitan (France)
	Lang=0482
If LangName=Oriya (India)
	Lang=0448
If LangName=Pashto (Afghanistan)
	Lang=0463
If LangName=Persian
	Lang=0429
If LangName=Polish
	Lang=0415
If LangName=Portuguese (Brazilian)
	Lang=0416
If LangName=Portuguese (Standard)
	Lang=0816
If LangName=Punjabi
	Lang=0446
If LangName=Quechua (Bolivia)
	Lang=046B
If LangName=Quechua (Ecuador)
	Lang=086B
If LangName=Quechua (Peru)
	Lang=0C6B
If LangName=Romanian
	Lang=0418
If LangName=Romansh (Switzerland)
	Lang=0417
If LangName=Russian
	Lang=0419
If LangName=Sami, Inari (Finland)
	Lang=243B
If LangName=Sami, Lule (Norway)
	Lang=103B
If LangName=Sami, Lule (Sweden)
	Lang=143B
If LangName=Sami, Northern (Finland)
	Lang=0C3B
If LangName=Sami, Northern (Norway)
	Lang=043B
If LangName=Sami, Northern (Sweden)
	Lang=083B
If LangName=Sami, Skolt (Finland)
	Lang=203B
If LangName=Sami, Southern (Norway)
	Lang=183B
If LangName=Sami, Southern (Sweden)
	Lang=1C3B
If LangName=Sanskrit
	Lang=044F
If LangName=Serbian (Cyrillic)
	Lang=0C1A
If LangName=Serbian (Latin)
	Lang=081A
If LangName=Serbian (Cyrillic, Bosnia and Herzegovina)
	Lang=1C1A
If LangName=Serbian (Cyrillic, Serbia)
	Lang=0C1A
If LangName=Serbian (Latin, Bosnia and Herzegovina)
	Lang=181A
If LangName=Serbian (Latin, Serbia)
	Lang=081A
If LangName=Sesotho sa Leboa (South Africa)
	Lang=046C
If LangName=Setswana (South Africa)
	Lang=0432
If LangName=Sinhala (Sri Lanka)
	Lang=045B
If LangName=Slovak
	Lang=041B
If LangName=Slovenian
	Lang=0424
If LangName=Spanish (Argentina)
	Lang=2C0A
If LangName=Spanish (Bolivia)
	Lang=400A
If LangName=Spanish (Chile)
	Lang=340A
If LangName=Spanish (Colombia)
	Lang=240A
If LangName=Spanish (Costa Rica)
	Lang=140A
If LangName=Spanish (Dominican Republic)
	Lang=1C0A
If LangName=Spanish (Ecuador)
	Lang=300A
If LangName=Spanish (El Salvador)
	Lang=440A
If LangName=Spanish (Guatemala)
	Lang=100A
If LangName=Spanish (Honduras)
	Lang=480A
If LangName=Spanish (Mexican)
	Lang=080A
If LangName=Spanish (Nicaragua)
	Lang=4C0A
If LangName=Spanish (Panama)
	Lang=180A
If LangName=Spanish (Paraguay)
	Lang=3C0A
If LangName=Spanish (Peru)
	Lang=280A
If LangName=Spanish (Puerto Rico)
	Lang=500A
If LangName=Spanish (Spain)
	Lang=0C0A
If LangName=Spanish (United States)
	Lang=540A
If LangName=Spanish (Uruguay)
	Lang=380A
If LangName=Spanish (Venezuela)
	Lang=200A
If LangName=Swahili
	Lang=0441
If LangName=Swedish (Finland)
	Lang=081D
If LangName=Swedish
	Lang=041D
If LangName=Syriac
	Lang=045A
If LangName=Tajik (Cyrillic, Tajikistan)
	Lang=0428
If LangName=Tamazight (Latin, Algeria)
	Lang=085F
If LangName=Tamil
	Lang=0449
If LangName=Tatar
	Lang=0444
If LangName=Telugu
	Lang=044A
If LangName=Thai
	Lang=041E
If LangName=Tibetan (PRC)
	Lang=0451
If LangName=Turkish
	Lang=041F
If LangName=Turkmen (Turkmenistan)
	Lang=0442
If LangName=Uighur (PRC)
	Lang=0480
If LangName=Ukrainian
	Lang=0422
If LangName=Upper Sorbian (Germany)
	Lang=042E
If LangName=Urdu
	Lang=0420
If LangName=Uzbek (Cyrillic)
	Lang=0843
If LangName=Uzbek (Latin)
	Lang=0443
If LangName=Vietnamese
	Lang=042A
If LangName=Welsh (United Kingdom)
	Lang=0452
If LangName=Wolof (Senegal)
	Lang=0488
If LangName=Yakut (Russia)
	Lang=0485
If LangName=Yi (PRC)
	Lang=0478
If LangName=Yoruba (Nigeria)
	Lang=046A
return Lang
}