/*	InKey script to provide a keyboard layout for Russian Phonetic Unicode
	  Autogenerated by InKeyKeyboardCreator 2.1.0; manually edited to handle case.

	Keyboard:	Russian Phonetic Unicode
	Version:    2.0
	Author:     Ben Chenoweth
	Official Distribution: http://inkeysoftware.com

*/

;________________________________________________________________________________________________________________
; This section is required at the top of every InKey keyboard script:

K_MinimumInKeyLibVersion = 1.912
	  ; The version number of the InKeyLib.ahki file that the keyboard developer used while writing this script.
	  ; It can be found near the top of the InKeyLib.ahki file.
	  ; It may be lower than the InKey version number.
	  ; If a user has an older version of InKeyLib.ahki, he will need to update it in order to use this keyboard script.
	  ; This protects your script from crashing from attempting to use functionality not present in older versions of InKeyLib.ahki.

K_UseContext = 2  ; Causes uncaptured character keys to be included in the context too. CAPS-sensitive.

#include InKeyLib.ahki
;________________________________________________________________________________________________________________

$+q::
$q::Send(UseUpperCase() ? "Ш" : "ш")

$+w::
$w::Send(UseUpperCase() ? "Щ" : "щ")

$+e::
$e::InCase(MultiTapSend(UseUpperCase() ? "Е Э" : "е э"))

$+r::
$r::Send(UseUpperCase() ? "Р" : "р")

$+t::
$t::InCase(MultiTapSend(UseUpperCase() ? "Т Ц" : "т ц"))

$+y::
$y::Send(UseUpperCase() ? "Й" : "й")

$+u::
$u::InCase(MultiTapSend(UseUpperCase() ? "У Ю" : "у ю"))

$+i::
$i::InCase(MultiTapSend(UseUpperCase() ? "И Ы" : "и ы"))

$+o::
$o::InCase(MultiTapSend(UseUpperCase() ? "О Ё" : "о ё"))

$+p::
$p::Send(UseUpperCase() ? "П" : "п")

$+a::
$a::InCase(MultiTapSend(UseUpperCase() ? "А Я" : "а я"))

$+s::
$s::Send(UseUpperCase() ? "С" : "с")

$+d::
$d::Send(UseUpperCase() ? "Д" : "д")

$+f::
$f::Send(UseUpperCase() ? "Ф" : "ф")

$+g::
$g::Send(UseUpperCase() ? "Г" : "г")

$+h::
$h::InCase(MultiTapSend(UseUpperCase() ? "Ь Ъ" : "ь ъ"))

$+j::
$j::Send(UseUpperCase() ? "Ж" : "ж")

$+k::
$k::Send(UseUpperCase() ? "К" : "к")

$+l::
$l::Send(UseUpperCase() ? "Л" : "л")

$+z::
$z::Send(UseUpperCase() ? "З" : "з")

$+x::
$x::Send(UseUpperCase() ? "Х" : "х")

$+c::
$c::Send(UseUpperCase() ? "Ч" : "ч")

$+v::
$v::Send(UseUpperCase() ? "В" : "в")

$+b::
$b::Send(UseUpperCase() ? "Б" : "б")

$+n::
$n::Send(UseUpperCase() ? "Н" : "н")

$+m::
$m::Send(UseUpperCase() ? "М" : "м")
