/*	InKey script to provide a keyboard layout for Khinalugh Keyboard
	  Autogenerated by InKeyKeyboardCreator 2.1.0

	Keyboard:	Khinalugh
	Version:
	Author:     Jung-Hoon Lee
	Official Distribution: http://inkeysoftware.com

*/

;________________________________________________________________________________________________________________
; This section is required at the top of every InKey keyboard script:

K_MinimumInKeyLibVersion = 1.912
	  ; The version number of the InKeyLib.ahki file that the keyboard developer used while writing this script.
	  ; It can be found near the top of the InKeyLib.ahki file.
	  ; It may be lower than the InKey version number.
	  ; If a user has an older version of InKeyLib.ahki, he will need to update it in order to use this keyboard script.
	  ; This protects your script from crashing from attempting to use functionality not present in older versions of InKeyLib.ahki.

K_UseContext = 1  ; Causes uncaptured character keys to be included in the context too. CAPS-sensitive.

#include InKeyLib.ahki
;________________________________________________________________________________________________________________


;________________________________________________________________________________________________________________
;________________________________________________________________________________________________________________
; SMALL LETTERS
;________________________________________________________________________________________________________________
;________________________________________________________________________________________________________________

$`::Send("`")

$1::Send("1")

$2::Send("2")

$3::Send("3")

$4::Send("4")

$5::Send("5")

$6::Send("6")

$7::Send("7")

$8::Send("8")

$9::Send("9")

$0::Send("0")

$-::Send("-")

$=::Send("=")

$\::Send("\")

$q::InCase(MultiTapSend("q q̂ q̇"))

$w::Send("ü")

$e::Send("e")

$r::Send("r")

$t::InCase(MultiTapSend("t t̂ ṫ"))

$y::Send("y")

$u::Send("u")

$i::Send("i")

$o::Send("o")

$p::InCase(MultiTapSend("p p̂ ṗ"))

$[::Send("ö")

$]::InCase(MultiTapSend("ğ ĝ"))

$a::Send("a")

$s::InCase(MultiTapSend("s ŝ"))

$d::Send("d")

$f::Send("f")

$g::Send("g")

$h::InCase(MultiTapSend("h ĥ ḣ"))

$j::Send("j")

$k::InCase(MultiTapSend("k k̂ k̇"))

$l::Send("l")

$`;::Send("ı")

$'::Send("ə")

$z::InCase(MultiTapSend("z ẑ ż"))

$x::InCase(MultiTapSend("x x̂"))

$c::Send("c")

$v::Send("v")

$b::Send("b")

$n::Send("n")

$m::Send("m")

$,::InCase(MultiTapSend("ç ĉ ċ"))

$.::Send("ş")

$/::Send(".")



;________________________________________________________________________________________________________________
;________________________________________________________________________________________________________________
; CAPITAL LETTERS -- i.e. when pressed with SHIFT key
;________________________________________________________________________________________________________________
;________________________________________________________________________________________________________________

$~::Send("~")

$!::Send("!")

$@::Send("“")

$#::Send("Ⅶ")

$$::Send(";")

$%::Send("%")

$^::Send(":")

$&::Send("?")

$*::Send("*")

$(::Send("(")

$)::Send(")")

$_::Send("_")

$+::Send("+")

$|::Send("|")

$+q::InCase(MultiTapSend("Q Q̂ Q̇"))

$+w::Send("Ü")

$+e::Send("E")

$+r::Send("R")

$+t::InCase(MultiTapSend("T T̂ Ṫ"))

$+y::Send("Y")

$+u::Send("U")

$+i::Send("İ")

$+o::Send("O")

$+p::InCase(MultiTapSend("P P̂ Ṗ"))

${::Send("Ö")

$}::InCase(MultiTapSend("Ğ Ĝ"))

$+a::Send("A")

$+s::InCase(MultiTapSend("S Ŝ"))

$+d::Send("D")

$+f::Send("F")

$+g::Send("G")

$+h::InCase(MultiTapSend("H Ĥ Ḣ"))

$+j::Send("J")

$+k::InCase(MultiTapSend("K K̂ K̇"))

$+l::Send("L")

$+`;::Send("I")

$"::Send("Ə")

$+z::InCase(MultiTapSend("Z Ẑ Ż"))

;$+x::Send("X")
$+x::InCase(MultiTapSend("X X̂"))

$+c::Send("C")

$+v::Send("V")

$+b::Send("B")

$+n::Send("N")

$+m::Send("M")

$<::InCase(MultiTapSend("Ç Ĉ Ċ"))

$>::Send("Ş")

$?::Send(",")
