/*	InKey script to provide a keyboard layout for Cipher Music Unicode
	  Autogenerated by InKeyKeyboardCreator

	Keyboard:	Cipher Music Unicode
	Version:    1.0
	Author:
	Official Distribution: http://inkeysoftware.com

*/

;________________________________________________________________________________________________________________
; This section is required at the top of every InKey keyboard script:

K_MinimumInKeyLibVersion = 0.092
	  ; The version number of the InKeyLib.ahki file that the keyboard developer used while writing this script.
	  ; It can be found near the top of the InKeyLib.ahki file.
	  ; It may be lower than the InKey version number.
	  ; If a user has an older version of InKeyLib.ahki, he will need to update it in order to use this keyboard script.
	  ; This protects your script from crashing from attempting to use functionality not present in older versions of InKeyLib.ahki.

K_UseContext = 1  ; Causes uncaptured character keys to be included in the context too.

#include InKeyLib.ahki
;________________________________________________________________________________________________________________


OnLoadScript:
RegisterRota(1, "1 1̇ 1̣ 1̸ 1̸̇ 1̸̣", 0x31, 0, 0, 8)  ;| 1 1̇ 1̣ 1̸ 1̸̇ 1̸̣
RegisterRota(2, "2 2̇ 2̣ 2̸ 2̸̇ 2̸̣", 0x32, 0, 0, 8)  ;| 2 2̇ 2̣ 2̸ 2̸̇ 2̸̣
RegisterRota(3, "3 3̇ 3̣ 3̸ 3̸̇ 3̸̣", 0x33, 0, 0, 8)  ;| 3 3̇ 3̣ 3̸ 3̸̇ 3̸̣
RegisterRota(4, "4 4̇ 4̣ 4̸ 4̸̇ 4̸̣", 0x34, 0, 0, 8)  ;| 4 4̇ 4̣ 4̸ 4̸̇ 4̸̣
RegisterRota(5, "5 5̇ 5̣ 5̸ 5̸̇ 5̸̣", 0x35, 0, 0, 8)  ;| 5 5̇ 5̣ 5̸ 5̸̇ 5̸̣
RegisterRota(6, "6 6̇ 6̣ 6̸ 6̸̇ 6̸̣", 0x36, 0, 0, 8)  ;| 6 6̇ 6̣ 6̸ 6̸̇ 6̸̣
RegisterRota(7, "7 7̇ 7̣ 7⃥ 7⃥̇ 7⃥̣", 0x37, 0, 0, 8)  ;| 7 7̇ 7̣ 7⃥ 7⃥̇ 7⃥̣
RegisterRota(8, "8 ♭ ♯ ♮", 0x38, 0, 0, 8)  ;| 8 ♭ ♯ ♮
RegisterRota(9, "9 á ó ú é í", 0x39, 0, 0, 8)  ;| 9 á ó ú é í
RegisterRota(10, "- ̅ ̲", 0x2D, 0, 0, 8)  ;| - ̅ ̲
RegisterRota(11, "= ̿ ̳", 0x3D, 0, 0, 8)  ;| = ̿ ̳
RegisterRota(12, "͒ ^", 0x352, 0, 0, 8)  ;| ͒ ^
RegisterRota(13, "( Á Ó Ú É Í", 0x28, 0, 0, 8)  ;| ( Á Ó Ú É Í
RegisterRota(14, "“ ‘ <", 0x201C, 0, 0, 8)  ;| “ ‘ <
RegisterRota(15, "” ’ >", 0x201D, 0, 0, 8)  ;| ” ’ >
return
;________________________________________________________________________________________________________________

$1::
DoRota(1)
return
$2::
DoRota(2)
return
$3::
DoRota(3)
return
$4::
DoRota(4)
return
$5::
DoRota(5)
return
$6::
DoRota(6)
return
$7::
DoRota(7)
return
$8::
DoRota(8)
return
$9::
DoRota(9)
return
$-::
DoRota(10)
return
$=::
DoRota(11)
return
$^::
DoRota(12)
return
$(::
DoRota(13)
return
${::
SendChar(0xD834)  ;| �
SendChar(0xDD77)  ;| �
return
$}::
SendChar(0xD834)  ;| �
SendChar(0xDD78)  ;| �
return
$<::
DoRota(14)
return
$>::
DoRota(15)
return
$^.:: SendChar(0xB7)  ;| ·
$^!::
SendChar(0xD834)  ;| �
SendChar(0xDD00)  ;| �
return
$^@::
SendChar(0xD834)  ;| �
SendChar(0xDD01)  ;| �
return
$^#::
SendChar(0xD834)  ;| �
SendChar(0xDD03)  ;| �
return
$^$::
SendChar(0xD834)  ;| �
SendChar(0xDD02)  ;| �
return
$^%::
SendChar(0xD834)  ;| �
SendChar(0xDD06)  ;| �
return
$^^::
SendChar(0xD834)  ;| �
SendChar(0xDD07)  ;| �
return
$^{:: SendChar(0x7B)  ;| {
$^}:: SendChar(0x7D)  ;| }
$^"::
SendChar(0xD834)  ;| �
SendChar(0xDD12)  ;| �
return
$^>:: SendChar(0x323)  ;| ̣
