/*	InKey script to provide a keyboard layout for Anadolu
	  Autogenerated by InKeyKeyboardCreator

	Keyboard:	Anadolu
	Version:    1.0
	Author:
	Official Distribution: http://inkeysoftware.com

*/

;________________________________________________________________________________________________________________
; This section is required at the top of every InKey keyboard script:

K_MinimumInKeyLibVersion = 0.092
	  ; The version number of the InKeyLib.ahki file that the keyboard developer used while writing this script.
	  ; It can be found near the top of the InKeyLib.ahki file.
	  ; It may be lower than the InKey version number.
	  ; If a user has an older version of InKeyLib.ahki, he will need to update it in order to use this keyboard script.
	  ; This protects your script from crashing from attempting to use functionality not present in older versions of InKeyLib.ahki.

K_UseContext = 1  ; Causes uncaptured character keys to be included in the context too.

#include InKeyLib.ahki
;________________________________________________________________________________________________________________


OnLoadScript:
RegisterRota(1, "e ê", 0x65, 0, 0, 8)  ;| e ê
RegisterRota(2, "u ü û", 0x75, 0, 0, 8)  ;| u ü û
RegisterRota(3, "i ı î", 0x69, 0, 0, 8)  ;| i ı î
RegisterRota(4, "o ö", 0x6F, 0, 0, 8)  ;| o ö
RegisterRota(5, "a â", 0x61, 0, 0, 8)  ;| a â
RegisterRota(6, "s ş", 0x73, 0, 0, 8)  ;| s ş
RegisterRota(7, "g ğ", 0x67, 0, 0, 8)  ;| g ğ
RegisterRota(8, "c ç", 0x63, 0, 0, 8)  ;| c ç
RegisterRota(9, "E Ê", 0x45, 0, 0, 8)  ;| E Ê
RegisterRota(10, "U Ü Û", 0x55, 0, 0, 8)  ;| U Ü Û
RegisterRota(11, "I İ Î", 0x49, 0, 0, 8)  ;| I İ Î
RegisterRota(12, "O Ö", 0x4F, 0, 0, 8)  ;| O Ö
RegisterRota(13, "A Â", 0x41, 0, 0, 8)  ;| A Â
RegisterRota(14, "S Ş", 0x53, 0, 0, 8)  ;| S Ş
RegisterRota(15, "G Ğ", 0x47, 0, 0, 8)  ;| G Ğ
RegisterRota(16, "C Ç", 0x43, 0, 0, 8)  ;| C Ç
return
;________________________________________________________________________________________________________________

$e::
DoRota(1)
return
$u::
DoRota(2)
return
$i::
DoRota(3)
return
$o::
DoRota(4)
return
$a::
DoRota(5)
return
$s::
DoRota(6)
return
$g::
DoRota(7)
return
$c::
DoRota(8)
return
$+e::
DoRota(9)
return
$+u::
DoRota(10)
return
$+i::
DoRota(11)
return
$+o::
DoRota(12)
return
$+a::
DoRota(13)
return
$+s::
DoRota(14)
return
$+g::
DoRota(15)
return
$+c::
DoRota(16)
return
