/*	InKey script autogenerated by InKeyKeyboardCreator

	Keyboard:	CAB2

*/

K_MinimumInKeyLibVersion = 0.092
K_UseContext = 1

#include InKeyLib.ahki


OnLoadScript:
rota =
( C %
	a á a̱	;
	e é e̱	;
	i í i̱	;
	n ñ n̈	;
	o ó o̱	;
	s s̈	;
	u ú ü u̱	;
	x ẍ	;
	A Á A̱	;
	E É E̱	;
	I Í I̱	;
	N Ñ N̈	;
	O Ó O̱	;
	S S̈	;
	U Ú Ü U̱	;
	X Ẍ	;
)
RegisterRota(1, "= — –", 0x3D, 0,0,1)
RegisterRota(2, rota, 0x5B, 0, 0x5B)
RegisterRota(3, "! ¡", 0x21, 0, 0, 1)
RegisterRota(4, "< « ‹ ‘ “", 0x3C, 0, 0, 1)
RegisterRota(5, "> » ’ ”", 0x3E, 0, 0, 1)
RegisterRota(6, "? ¿", 0x3F, 0, 0, 1)
RegisterRota(7, "u ʉ ʉ̃ ʉ̃́	U Ʉ Ʉ̃ Ʉ̃́", 0x5D, 0, 0, 1)
RegisterRota(8, "' ꞌ ß ", 0x27, 0, 0, 1)
return

$=:: DoRota(1)
$[:: DoRota(2)
$!:: DoRota(3)
$<:: DoRota(4)
$>:: DoRota(5)
$?:: DoRota(6)
$]:: DoRota(7)
$':: DoRota(8)
