/*	InKey script to provide a keyboard layout for Test
	  Autogenerated by InKeyKeyboardCreator

	Keyboard:	Test
	Version:    1.0
	Author:
	Official Distribution: http://inkeysoftware.com

*/

;________________________________________________________________________________________________________________
; This section is required at the top of every InKey keyboard script:

K_MinimumInKeyLibVersion = 0.092
	  ; The version number of the InKeyLib.ahki file that the keyboard developer used while writing this script.
	  ; It can be found near the top of the InKeyLib.ahki file.
	  ; It may be lower than the InKey version number.
	  ; If a user has an older version of InKeyLib.ahki, he will need to update it in order to use this keyboard script.
	  ; This protects your script from crashing from attempting to use functionality not present in older versions of InKeyLib.ahki.

K_UseContext = 1  ; Causes uncaptured character keys to be included in the context too.

#include InKeyLib.ahki
;________________________________________________________________________________________________________________

OnLoadScript:

Vowels = aAeEiIoOuU
Comb_T     = 0x0303
Comb_A     = 0x0301
Comb_D     = 0x0323
Comb_Mark  = 0x0303 0x0301 0x0323

return


$~::
cc  := ctx()
cc2  := ctx(2)
cc3  := ctx(3)
cc4  := ctx(4)
	SetFormat, integer, hex
	cc += 0
	cc2 += 0
	cc3 += 0
	cc4 += 0
	SetFormat, integer, d
TrayTipQ( cc4 " " cc3 " " cc2 " " cc ,,5000)
if (IsVowel(cc))
{
   SendChar(Comb_T)
}
else if (IsCombMark(cc) or (cc = 0x7E))		; Only need to look further back on context in these cases
{
	cc2 := ctx(2)
	if (IsVowel(cc2))
	{
		if ((cc = 0x301) or (cc = 0x323))
		{	; One other combining mark already present; no reordering needed
			SendChar(0x303)
		}
		else if (cc = 0x303)				; Combining tilde already there, so must be double-press of tilde
		{
			ReplaceChar(0x7E)
		}
		else 								; Must be ~ which inidicates a triple-press of ~
		{
			InsertChar(0x303)
		}
	}
	else if (IsCombMark(cc2))				; Only need to look further back on context in this case
	{
		cc3 := ctx(3)
		if(IsVowel(cc3))						; Due to reordering, cc can only be ~, Comb tilde or Comb acute
		{
			if (cc = 0x7E)								; ~ which inidicates a triple-press of ~
			{	if (cc2 = 0x323)
				{
					InsertChar(0x303)
				}
				else
				{
					InsertChars(0x303,2,2)
				}
			}
			else if (cc = 0x301)					; Just add combining tilde
			{
				SendChar(0x303)
			}
			else 									; cc must be Comb tilde, so treat as triple press if that was from last keystroke
			{
				ReplaceChar(0x7E)
			}
		}
		else if (IsCombMark(cc3))				; Only need to look further back on context in this case
		{
			cc4 := ctx(4)
			if (IsVowel(cc4))				; Only valid options are Vowel, Comb dot, Comb acute with tilde or comb tilde
			{
				if (cc = 0x303)
				{
					ReplaceChar(0x7E)
				}
				else
				{
					InsertChars(0x303,3,3)
				}
			}
		}
	}
}
return

IsVowel(c) {
   if ((c = 0x41) or (c = 0x45) or (c = 0x49) or (c = 0x4F) or (c = 0x55) or (c = 0x61) or (c = 0x65) or (c = 0x69) or (c = 0x6F) or (c = 0x75))
	  return 1
   else
	  return 0
   return
}

IsCombMark(c) {
   if ((c = 0x303) or (c = 0x301) or (c = 0x323)) ; Combining ~, ' or ^
	  return 1
   else
	  return 0
   return
}

IsDiaKey(c) {
   if ((c = 0x7E) or (c = 0x27) or (c = 0x5E)) ; ~, ' or ^
	  return 1
   else
	  return 0
   return
}