/*InKey Script to provide a context-sensitive keyboard layout for IPA

	Keyboard:	IPA Unicode
	Version:	1.06
	Authors:	Benjamin of NLCI, and Dan of SAG.
	Official Distributionː	http://inkeysoftware.com

	You are free to modify this script for your own purposes.
	Please retain the above authorship details as appropriate.

HISTORY:
2008-08-13  0.1  Created by NLCI and SAG, to mimic SIL's IPAUni12.KMN layout
2008-09-01  1.0  Shortcuts for ligatures added
2008-10-14  1.01 Comments in continuation sections adjusted to avoid AHK's bug.
2008-10-28  1.02 K_MinimumInKeyLibVersion specified
2008-11-19  1.03 Make use of default hotkeys (requires InKeyLib 0.092)
2009-03-01  1.04 The ampersand (&) key now joins/splits these chars when typed after them: 	ʣ ʤ ʥ ʦ ʧ ʨ ʩ ʪ ʫ ɮ
2009-11-10  1.05 This keyboard now outputs only NFD forms, in order to keep FieldWorks apps from misbehaving.
2011-04-07  1.06 Updated to use CAPSLOCK-sensitive context

*/

;________________________________________________________________________________________________________________
; This section is required at the top of every InKey keyboard script:

K_MinimumInKeyLibVersion = 0.102
	; The version number of the InKeyLib.ahki file that the keyboard developer used while writing this script.
	; It can be found near the top of the InKeyLib.ahki file.
	; It may be lower than the InKey version number.
	; If a user has an older version of InKeyLib.ahki, he will need to update it in order to use this keyboard script.
	; This protects your script from crashing from attempting to use functionality not present in older versions of InKeyLib.ahki.

K_UseContext = 2	; Causes uncaptured character keys to be included in the context too. CAPS-sensitive.

#include InKeyLib.ahki

;________________________________________________________________________________________________________________

; A caution regarding the use of comments in continuation sections, due to a quirk (or bug) of AutoHotKey:
; If the final non-whitespace character's value ends in hexidecimal 20, 60, A0, or E0, when AHK removes the in-line
; comment (along with the preceding whitespace), the final character will be corrupted.  (Geek note: The reason is
; that AutoHotKey is looking at the UTF-8 sequence, and the final byte in that sequence is character A0, a
; "non-breaking space" which AHK thus deletes as if it were extra whitespace before the comment.)
; One workaround is to move the comment to the following line.
; Comments generated by InsertUnicodeCmts.pl will be automatically repositioned on the next line if necessary.

;*** OnLoadScript Subroutine --------------------------------
OnLoadScript:	; InKeyLib will call this subroutine just once, when the script is first loaded, for any script initialization.
;		Perform any script-wide initialization here, such as calls to RegisterRota().

; The first few rotas are simple non-rotating changes that digits 0 through 4 effect, relating to tone marks.

; Key: Zero ( 0 )	- non-looping rota for tone marks
rota =
( C
	#	˩	;]	 ↚	 0023 |  02E9	 number_sign |  modifier_letter_extra-low_tone_bar
	&	꜒	;]	 ↚	 0026 |  A712	 ampersand |  modifier_letter_extra-high_left-stem_tone_bar
	̊	̏	;]	 ↚	 030A |  030F	 combining_ring_above |  combining_double_grave_accent
)
RegisterRota(0, rota, 0x30, 0, 0x30)	;|	digit_zero (0)  digit_zero (0)

; Key: One ( 1 )	- non-looping rota for tone marks
rota =
( C
	#	˨	;]	 ↚	 0023 |  02E8	 number_sign |  modifier_letter_low_tone_bar
	&	꜓	;]	 ↚	 0026 |  A713	 ampersand |  modifier_letter_high_left-stem_tone_bar
	̊	̀	;]	 ↚	 030A |  0300	 combining_ring_above |  combining_grave_accent
	̌	᷈	;]	 ↚	 030C |  1DC8	 combining_caron |  <???>
	̄	᷆	;]	 ↚	 0304 |  1DC6	 combining_macron |  <???>
	́	̂	;]	 ↚	 0301 |  0302	 combining_acute_accent |  combining_circumflex_accent
)
RegisterRota(1, rota, 0x31, 0, 0x31)	;|	digit_one (1)  digit_one (1)

; Key: Two ( 2 )	- non-looping rota for tone marks
rota =
( C
	#	˧	;]	 ↚	 0023 |  02E7	 number_sign |  modifier_letter_mid_tone_bar
	&	꜔	;]	 ↚	 0026 |  A714	 ampersand |  modifier_letter_mid_left-stem_tone_bar
	̊	̄	;]	 ↚	 030A |  0304	 combining_ring_above |  combining_macron
	̀	᷅	;]	 ↚	 0300 |  1DC5	 combining_grave_accent |  <???>
	́	᷇	;]	 ↚	 0301 |  1DC7	 combining_acute_accent |  <???>
)
RegisterRota(2, rota, 0x32, 0, 0x32)	;|	digit_two (2)  digit_two (2)

; Key Three (3)	- non-looping rota for tone marks
rota =
( C
	#	˦	;]	 ↚	 0023 |  02E6	 number_sign |  modifier_letter_high_tone_bar
	&	꜕	;]	 ↚	 0026 |  A715	 ampersand |  modifier_letter_low_left-stem_tone_bar
	̊	́	;]	 ↚	 030A |  0301	 combining_ring_above |  combining_acute_accent
	̀	̌	;]	 ↚	 0300 |  030C	 combining_grave_accent |  combining_caron
	̄	᷄	;]	 ↚	 0304 |  1DC4	 combining_macron |  <???>
	̂	᷉	;]	 ↚	 0302 |  1DC9	 combining_circumflex_accent |  <???>
)
RegisterRota(3, rota, 0x33, 0, 0x33)	;|	digit_three (3)  digit_three (3)

; Key: Four ( 4 )	- non-looping rota for tone marks
rota =
( C
	#	˥	;]	 ↚	 0023 |  02E5	 number_sign |  modifier_letter_extra-high_tone_bar
	&	꜖	;]	 ↚	 0026 |  A716	 ampersand |  modifier_letter_extra-low_left-stem_tone_bar
	̊	̋	;]	 ↚	 030A |  030B	 combining_ring_above |  combining_double_acute_accent
)
RegisterRota(4, rota, 0x34, 0, 0x34)	;|	digit_four (4)  digit_four (4)

; Key: Equals (=)   -This rota is the all-purpose "can't-remember-the-keystroke" rota.
; The first alternate mimics the behavior of IPAUni12.kmn, but otherwise we are free to order alternates as seems best.
; For a character that appears in more than one set, put the lesser set second, and make this character the last character
; in that set.  (After that, looping will move to the major set.)
rota =
( C %
	\	=		;]	 ↚	 005C |  003D	 reverse_solidus |  equals_sign
	̟ +			;]	 ⇔	 031F |  002B	 combining_plus_sign_below |  plus_sign
	̪ {			;]	 ⇔	 032A |  007B	 combining_bridge_below |  left_curly_bracket
	ˈ }			;]	 ⇔	 02C8 |  007D	 modifier_letter_vertical_line |  right_curly_bracket
	̠ _			;]	 ⇔	 0320 |  005F	 combining_minus_sign_below |  low_line
	ː :			;]	 ⇔	 02D0 |  003A	 modifier_letter_triangular_colon |  colon
	̃ ~			;]	 ⇔	 0303 |  007E	 combining_tilde |  tilde
	̈ *			;]	 ⇔	 0308 |  002A	 combining_diaeresis |  asterisk
	̊ @			;]	 ⇔	 030A |  0040	 combining_ring_above |  commercial_at
	̥ %			;]	 ⇔	 0325 |  0025	 combining_ring_below |  percent_sign
	̩ $			;]	 ⇔	 0329 |  0024	 combining_vertical_line_below |  dollar_sign
	# ‿			;]	 ⇔	 0023 |  203F	 number_sign |  undertie
	. ‖			;]	 ⇔	 002E |  2016	 full_stop |  double_vertical_line
	ǃ ǂ !			;]	 ⇔	 01C3 |  01C2 |  0021	 latin_letter_retroflex_click |  latin_letter_alveolar_click |  exclamation_mark
	? ʔ ʕ ʡ ʢ		;]	 ⇔	 003F |  0294 |  0295 |  02A1 |  02A2	 question_mark |  latin_letter_glottal_stop |  latin_letter_pharyngeal_voiced_fricative |  latin_letter_glottal_stop_with_stroke |  latin_letter_reversed_glottal_stop_with_stroke
	a ɑ ɐ æ ᴂ α ᶏ ᶐ ᴀ	;]	 ⇔	 0061 |  0251 |  0250 |  00E6 |  1D02 |  03B1 |  1D8F |  1D90 |  1D00	 latin_small_letter_a |  latin_small_letter_alpha |  latin_small_letter_turned_a |  latin_small_letter_ae |  latin_small_letter_turned_ae |  greek_small_letter_alpha |  latin_small_letter_a_with_retroflex_hook |  latin_small_letter_alpha_with_retroflex_hook |  latin_letter_small_capital_a
	ae æ ᴂ	aə	;]	 ↚	 0061 0065 |  00E6 |  1D02 |  0061 0259	 latin_small_letter_a latin_small_letter_e |  latin_small_letter_ae |  latin_small_letter_turned_ae |  latin_small_letter_a latin_small_letter_schwa
	A	ᴂ		;]	 ↚	 0041 |  1D02	 latin_capital_letter_a |  latin_small_letter_turned_ae
	b β ɓ ᶀ ᵬ	;]	 ⇔	 0062 |  03B2 |  0253 |  1D80 |  1D6C	 latin_small_letter_b |  greek_small_letter_beta |  latin_small_letter_b_with_hook |  latin_small_letter_b_with_palatal_hook |  latin_small_letter_b_with_middle_tilde
	B ʙ			;]	 ⇔	 0042 |  0299	 latin_capital_letter_b |  latin_letter_small_capital_b
	c ç ƈ ɕ		;]	 ⇔	 0063 |  0063 0327 |  0188 |  0255	 latin_small_letter_c |  latin_small_letter_c combining_cedilla |  latin_small_letter_c_with_hook |  latin_small_letter_c_with_curl
	d ð ɗ ɖ ȡ ᶑ ᶁ ᵭ	;]	 ⇔	 0064 |  00F0 |  0257 |  0256 |  0221 |  1D91 |  1D81 |  1D6D	 latin_small_letter_d |  latin_small_letter_eth |  latin_small_letter_d_with_hook |  latin_small_letter_d_with_tail |  latin_small_letter_d_with_curl |  latin_small_letter_d_with_hook_and_tail |  latin_small_letter_d_with_palatal_hook |  latin_small_letter_d_with_middle_tilde
	OE	ɶ		;]	 ↚	 004F 0045 |  0276	 latin_capital_letter_o latin_capital_letter_e |  latin_letter_small_capital_oe
	E ɘ ɶ œ ᴇ	;]	 ⇔	 0045 |  0258 |  0276 |  0153 |  1D07	 latin_capital_letter_e |  latin_small_letter_reversed_e |  latin_letter_small_capital_oe |  latin_small_ligature_oe |  latin_letter_small_capital_e
	oe œ	oə		;]	 ↚	 006F 0065 |  0153 |  006F 0259	 latin_small_letter_o latin_small_letter_e |  latin_small_ligature_oe |  latin_small_letter_o latin_small_letter_schwa
	e ə ɜ ɛ ʚ œ ᶒ ᶓ ᶔ ᶕ ɘ	;]	 ⇔	 0065 |  0259 |  025C |  025B |  029A |  0153 |  1D92 |  1D93 |  1D94 |  1D95 |  0258	 latin_small_letter_e |  latin_small_letter_schwa |  latin_small_letter_reversed_open_e |  latin_small_letter_open_e |  latin_small_letter_closed_open_e |  latin_small_ligature_oe |  latin_small_letter_e_with_retroflex_hook |  latin_small_letter_open_e_with_retroflex_hook |  latin_small_letter_reversed_open_e_with_retroflex_hook |  latin_small_letter_schwa_with_retroflex_hook |  latin_small_letter_reversed_e
	f ɸ ᶂ ᵮ		;]	 ⇔	 0066 |  0278 |  1D82 |  1D6E	 latin_small_letter_f |  latin_small_letter_phi |  latin_small_letter_f_with_palatal_hook |  latin_small_letter_f_with_middle_tilde
	g ɣ ɡ ɠ ᶃ	;]	 ⇔	 0067 |  0263 |  0261 |  0260 |  1D83	 latin_small_letter_g |  latin_small_letter_gamma |  latin_small_letter_script_g |  latin_small_letter_g_with_hook |  latin_small_letter_g_with_palatal_hook
	G ɢ ʛ		;]	 ⇔	 0047 |  0262 |  029B	 latin_capital_letter_g |  latin_letter_small_capital_g |  latin_letter_small_capital_g_with_hook
	h ɥ ħ ɦ ђ ɧ	;]	 ⇔	 0068 |  0265 |  0127 |  0266 |  0452 |  0267	 latin_small_letter_h |  latin_small_letter_turned_h |  latin_small_letter_h_with_stroke |  latin_small_letter_h_with_hook |  cyrillic_small_letter_dje |  latin_small_letter_heng_with_hook
	H ʜ			;]	 ⇔	 0048 |  029C	 latin_capital_letter_h |  latin_letter_small_capital_h
	i ɪ ɩ ɨ ᵼ ᵻ ᶖ	;]	 ⇔	 0069 |  026A |  0269 |  0268 |  1D7C |  1D7B |  1D96	 latin_small_letter_i |  latin_letter_small_capital_i |  latin_small_letter_iota |  latin_small_letter_i_with_stroke |  latin_small_letter_iota_with_stroke |  latin_small_capital_letter_i_with_stroke |  latin_small_letter_i_with_retroflex_hook
	I ɨ			;]	 ⇔	 0049 |  0268	 latin_capital_letter_i |  latin_small_letter_i_with_stroke
	j ɟ ʄ ʝ		;]	 ⇔	 006A |  025F |  0284 |  029D	 latin_small_letter_j |  latin_small_letter_dotless_j_with_stroke |  latin_small_letter_dotless_j_with_stroke_and_hook |  latin_small_letter_j_with_crossed-tail
	k ƙ ᶄ		;]	 ⇔	 006B |  0199 |  1D84	 latin_small_letter_k |  latin_small_letter_k_with_hook |  latin_small_letter_k_with_palatal_hook
	l ɬ ɮ ɭ ȴ ɺ ʎ ᶅ ɫ	;]	 ⇔	 006C |  026C |  026E |  026D |  0234 |  027A |  028E |  1D85 |  026B	 latin_small_letter_l |  latin_small_letter_l_with_belt |  latin_small_letter_lezh |  latin_small_letter_l_with_retroflex_hook |  latin_small_letter_l_with_curl |  latin_small_letter_turned_r_with_long_leg |  latin_small_letter_turned_y |  latin_small_letter_l_with_palatal_hook |  latin_small_letter_l_with_middle_tilde
	L ʟ ɺ		;]	 ⇔	 004C |  029F |  027A	 latin_capital_letter_l |  latin_letter_small_capital_l |  latin_small_letter_turned_r_with_long_leg
	m ɱ ᶆ ᵯ	;]	 ⇔	 006D |  0271 |  1D86 |  1D6F	 latin_small_letter_m |  latin_small_letter_m_with_hook |  latin_small_letter_m_with_palatal_hook |  latin_small_letter_m_with_middle_tilde
	n ɲ ŋ ɳ ȵ ᶇ ᵰ Ŋ	;]	 ⇔	 006E |  0272 |  014B |  0273 |  0235 |  1D87 |  1D70 |  014A	 latin_small_letter_n |  latin_small_letter_n_with_left_hook |  latin_small_letter_eng |  latin_small_letter_n_with_retroflex_hook |  latin_small_letter_n_with_curl |  latin_small_letter_n_with_palatal_hook |  latin_small_letter_n_with_middle_tilde |  latin_capital_letter_eng
	N ɴ Ŋ			;]	 ⇔	 004E |  0274 |  014A	 latin_capital_letter_n |  latin_letter_small_capital_n |  latin_capital_letter_eng
	O ɵ ɤ ɞ		;]	 ⇔	 004F |  0275 |  0264 |  025E	 latin_capital_letter_o |  latin_small_letter_barred_o |  latin_small_letter_rams_horn |  latin_small_letter_closed_reversed_open_e
	o ɒ ø ɔ ᶗ	;]	 ⇔	 006F |  0252 |  00F8 |  0254 |  1D97	 latin_small_letter_o |  latin_small_letter_turned_alpha |  latin_small_letter_o_with_stroke |  latin_small_letter_open_o |  latin_small_letter_open_o_with_retroflex_hook
	p ʘ ƥ ᶈ ᵱ	;]	 ⇔	 0070 |  0298 |  01A5 |  1D88 |  1D71	 latin_small_letter_p |  latin_letter_bilabial_click |  latin_small_letter_p_with_hook |  latin_small_letter_p_with_palatal_hook |  latin_small_letter_p_with_middle_tilde
	q ʠ
;]	 ⇔	 0071 |  02A0	 latin_small_letter_q |  latin_small_letter_q_with_hook	(No comments permitted on same line following ʠ)
	Q ʡ ʢ		;]	 ⇔	 0051 |  02A1 |  02A2	 latin_capital_letter_q |  latin_letter_glottal_stop_with_stroke |  latin_letter_reversed_glottal_stop_with_stroke
	R ʀ ʁ		;]	 ⇔	 0052 |  0280 |  0281	 latin_capital_letter_r |  latin_letter_small_capital_r |  latin_letter_small_capital_inverted_r
	r ɹ ɾ ɽ ɻ ᶉ ᵲ ᵳ		;]	 ⇔	 0072 |  0279 |  027E |  027D |  027B |  1D89 |  1D72 |  1D73	 latin_small_letter_r |  latin_small_letter_turned_r |  latin_small_letter_r_with_fishhook |  latin_small_letter_r_with_tail |  latin_small_letter_turned_r_with_hook |  latin_small_letter_r_with_palatal_hook |  latin_small_letter_r_with_middle_tilde |  latin_small_letter_r_with_fishhook_and_middle_tilde
;	ts ʧ	tʃ	;]	 ↚	 003B |  0074 0073 |  02A7 |  0074 0283	 semicolon |  latin_small_letter_t latin_small_letter_s |  latin_small_letter_tesh_digraph |  latin_small_letter_t latin_small_letter_esh
	s ʃ σ ʂ ᶊ ᵴ ᶘ ᶋ	;]	 ⇔	 0073 |  0283 |  03C3 |  0282 |  1D8A |  1D74 |  1D98 |  1D8B	 latin_small_letter_s |  latin_small_letter_esh |  greek_small_letter_sigma |  latin_small_letter_s_with_hook |  latin_small_letter_s_with_palatal_hook |  latin_small_letter_s_with_middle_tilde |  latin_small_letter_esh_with_retroflex_hook |  latin_small_letter_esh_with_palatal_hook
	S ᶘ			;]	 ⇔	 0053 |  1D98	 latin_capital_letter_s |  latin_small_letter_esh_with_retroflex_hook
	t θ ʇ ƭ ʈ ȶ ᵵ	;]	 ⇔	 0074 |  03B8 |  0287 |  01AD |  0288 |  0236 |  1D75	 latin_small_letter_t |  greek_small_letter_theta |  latin_small_letter_turned_t |  latin_small_letter_t_with_hook |  latin_small_letter_t_with_retroflex_hook |  latin_small_letter_t_with_curl |  latin_small_letter_t_with_middle_tilde
	T ʇ			;]	 ⇔	 0054 |  0287	 latin_capital_letter_t |  latin_small_letter_turned_t
	u ɯ ʉ ᵾ ʌ ʊ ɷ ʉ ᵾ ᶙ	;]	 ⇔	 0075 |  026F |  0289 |  1D7E |  028C |  028A |  0277 |  0289 |  1D7E |  1D99	 latin_small_letter_u |  latin_small_letter_turned_m |  latin_small_letter_u_bar |  latin_small_capital_letter_u_with_stroke |  latin_small_letter_turned_v |  latin_small_letter_upsilon |  latin_small_letter_closed_omega |  latin_small_letter_u_bar |  latin_small_capital_letter_u_with_stroke |  latin_small_letter_u_with_retroflex_hook
	U ʉ			;]	 ⇔	 0055 |  0289	 latin_capital_letter_u |  latin_small_letter_u_bar
	v ʋ ⱱ ᶌ		;]	 ⇔	 0076 |  028B |  2C71 |  1D8C	 latin_small_letter_v |  latin_small_letter_v_with_hook |  <???> |  latin_small_letter_v_with_palatal_hook
	w ʍ ɰ ⱳ	;]	 ⇔	 0077 |  028D |  0270 |  2C73	 latin_small_letter_w |  latin_small_letter_turned_w |  latin_small_letter_turned_m_with_long_leg |  <???>
	x χ ᶍ		;]	 ⇔	 0078 |  03C7 |  1D8D	 latin_small_letter_x |  greek_small_letter_chi |  latin_small_letter_x_with_palatal_hook
	y ʏ ɥ ʯ		;]	 ⇔	 0079 |  028F |  0265 |  02AF	 latin_small_letter_y |  latin_letter_small_capital_y |  latin_small_letter_turned_h |  latin_small_letter_turned_h_with_fishhook_and_tail
	Y ʯ			;]	 ⇔	 0059 |  02AF	 latin_capital_letter_y |  latin_small_letter_turned_h_with_fishhook_and_tail
	lz ɮ	lʒ		;]	 ↚	 006C 007A |  026E |  006C 0292	 latin_small_letter_l latin_small_letter_z |  latin_small_letter_lezh |  latin_small_letter_l latin_small_letter_ezh
;	dz ʤ	dʒ		;]	 ↚	 003B |  0064 007A |  02A4 |  0064 0292	 semicolon |  latin_small_letter_d latin_small_letter_z |  latin_small_letter_dezh_digraph |  latin_small_letter_d latin_small_letter_ezh
	z ʒ ᶚ ʑ ʐ ᶎ ᵶ ɿ ʅ	;]	 ⇔	 007A |  0292 |  1D9A |  0291 |  0290 |  1D8E |  1D76 |  027F |  0285	 latin_small_letter_z |  latin_small_letter_ezh |  latin_small_letter_ezh_with_retroflex_hook |  latin_small_letter_z_with_curl |  latin_small_letter_z_with_retroflex_hook |  latin_small_letter_z_with_palatal_hook |  latin_small_letter_z_with_middle_tilde |  latin_small_letter_reversed_r_with_fishhook |  latin_small_letter_squat_reversed_esh
	Z ᶚ			;]	 ⇔	 005A |  1D9A	 latin_capital_letter_z |  latin_small_letter_ezh_with_retroflex_hook
)
RegisterRota(5, rota, 0x3D, 0x3D)	;|	equals_sign (=)  equals_sign (=)

; right wedge ( > ) - A general set of alternate forms
rota =
( C
	\	>	;]	 ↚	 005C |  003E	 reverse_solidus |  greater-than_sign
	# ꜛ ↗	;]	 ⇔	 0023 |  A71B |  2197	 number_sign |  <???> |  north_east_arrow
	ǃ ǁ		;]	 ⇔	 01C3 |  01C1	 latin_letter_retroflex_click |  latin_letter_lateral_click
	= →	;]	 ⇔	 003D |  2192	 equals_sign |  rightwards_arrow
	A ᴂ		;]	 ⇔	 0041 |  1D02	 latin_capital_letter_a |  latin_small_letter_turned_ae
	a ɐ		;]	 ⇔	 0061 |  0250	 latin_small_letter_a |  latin_small_letter_turned_a
	b ɓ		;]	 ⇔	 0062 |  0253	 latin_small_letter_b |  latin_small_letter_b_with_hook
	c ƈ		;]	 ⇔	 0063 |  0188	 latin_small_letter_c |  latin_small_letter_c_with_hook
	d ɗ		;]	 ⇔	 0064 |  0257	 latin_small_letter_d |  latin_small_letter_d_with_hook
	E ɶ		;]	 ⇔	 0045 |  0276	 latin_capital_letter_e |  latin_letter_small_capital_oe
	e ɜ		;]	 ⇔	 0065 |  025C	 latin_small_letter_e |  latin_small_letter_reversed_open_e
	G ʛ		;]	 ⇔	 0047 |  029B	 latin_capital_letter_g |  latin_letter_small_capital_g_with_hook
	g ɠ
;]	 ⇔	 0067 |  0260	 latin_small_letter_g |  latin_small_letter_g_with_hook	(No comments permitted on same line following ɠ)
	H ɧ		;]	 ⇔	 0048 |  0267	 latin_capital_letter_h |  latin_small_letter_heng_with_hook
	h ħ		;]	 ⇔	 0068 |  0127	 latin_small_letter_h |  latin_small_letter_h_with_stroke
	I ᵼ		;]	 ⇔	 0049 |  1D7C	 latin_capital_letter_i |  latin_small_letter_iota_with_stroke
	j ʄ		;]	 ⇔	 006A |  0284	 latin_small_letter_j |  latin_small_letter_dotless_j_with_stroke_and_hook
	k ƙ		;]	 ⇔	 006B |  0199	 latin_small_letter_k |  latin_small_letter_k_with_hook
	L ɺ		;]	 ⇔	 004C |  027A	 latin_capital_letter_l |  latin_small_letter_turned_r_with_long_leg
	l ɮ		;]	 ⇔	 006C |  026E	 latin_small_letter_l |  latin_small_letter_lezh
	m ɱ		;]	 ⇔	 006D |  0271	 latin_small_letter_m |  latin_small_letter_m_with_hook
	n ŋ		;]	 ⇔	 006E |  014B	 latin_small_letter_n |  latin_small_letter_eng
	N Ŋ		;]	 ⇔	 004E |  014A	 latin_capital_letter_n |  latin_capital_letter_eng
	O ɤ		;]	 ⇔	 004F |  0264	 latin_capital_letter_o |  latin_small_letter_rams_horn
	o ø		;]	 ⇔	 006F |  00F8	 latin_small_letter_o |  latin_small_letter_o_with_stroke
	p ƥ		;]	 ⇔	 0070 |  01A5	 latin_small_letter_p |  latin_small_letter_p_with_hook
	q ʠ
;]	 ⇔	 0071 |  02A0	 latin_small_letter_q |  latin_small_letter_q_with_hook	(No comments permitted on same line following ʠ)
	R ʁ		;]	 ⇔	 0052 |  0281	 latin_capital_letter_r |  latin_letter_small_capital_inverted_r
	r ɾ		;]	 ⇔	 0072 |  027E	 latin_small_letter_r |  latin_small_letter_r_with_fishhook
	s σ		;]	 ⇔	 0073 |  03C3	 latin_small_letter_s |  greek_small_letter_sigma
	t ƭ		;]	 ⇔	 0074 |  01AD	 latin_small_letter_t |  latin_small_letter_t_with_hook
	u ʌ		;]	 ⇔	 0075 |  028C	 latin_small_letter_u |  latin_small_letter_turned_v
	U ᵾ		;]	 ⇔	 0055 |  1D7E	 latin_capital_letter_u |  latin_small_capital_letter_u_with_stroke
	w ɰ		;]	 ⇔	 0077 |  0270	 latin_small_letter_w |  latin_small_letter_turned_m_with_long_leg
	z ʑ		;]	 ⇔	 007A |  0291	 latin_small_letter_z |  latin_small_letter_z_with_curl
)
RegisterRota(6, rota, 0x3E, 0, 0x3E)	;|	greater-than_sign (>)  greater-than_sign (>)

; left wedge ( < )  - A general set of alternate forms
rota =
( C
	\	<	;]	 ↚	 005C |  003C	 reverse_solidus |  less-than_sign
	# ꜜ ↘	;]	 ⇔	 0023 |  A71C |  2198	 number_sign |  <???> |  south_east_arrow
	. |		;]	 ⇔	 002E |  007C	 full_stop |  vertical_line
	? ʕ		;]	 ⇔	 003F |  0295	 question_mark |  latin_letter_pharyngeal_voiced_fricative
	ǃ ǀ		;]	 ⇔	 01C3 |  01C0	 latin_letter_retroflex_click |  latin_letter_dental_click
	= ͏		;]	 ⇔	 003D |  034F	 equals_sign |  combining_grapheme_joiner
	a æ		;]	 ⇔	 0061 |  00E6	 latin_small_letter_a |  latin_small_letter_ae
	c ɕ		;]	 ⇔	 0063 |  0255	 latin_small_letter_c |  latin_small_letter_c_with_curl
	d ɖ		;]	 ⇔	 0064 |  0256	 latin_small_letter_d |  latin_small_letter_d_with_tail
	e ɛ		;]	 ⇔	 0065 |  025B	 latin_small_letter_e |  latin_small_letter_open_e
	E œ		;]	 ⇔	 0045 |  0153	 latin_capital_letter_e |  latin_small_ligature_oe
	g ɡ		;]	 ⇔	 0067 |  0261	 latin_small_letter_g |  latin_small_letter_script_g
	h ɦ		;]	 ⇔	 0068 |  0266	 latin_small_letter_h |  latin_small_letter_h_with_hook
	I ᵻ		;]	 ⇔	 0049 |  1D7B	 latin_capital_letter_i |  latin_small_capital_letter_i_with_stroke
	j ʝ		;]	 ⇔	 006A |  029D	 latin_small_letter_j |  latin_small_letter_j_with_crossed-tail
	l ɭ		;]	 ⇔	 006C |  026D	 latin_small_letter_l |  latin_small_letter_l_with_retroflex_hook
	L ʎ		;]	 ⇔	 004C |  028E	 latin_capital_letter_l |  latin_small_letter_turned_y
	n ɳ		;]	 ⇔	 006E |  0273	 latin_small_letter_n |  latin_small_letter_n_with_retroflex_hook
	o ɔ		;]	 ⇔	 006F |  0254	 latin_small_letter_o |  latin_small_letter_open_o
	O ɞ		;]	 ⇔	 004F |  025E	 latin_capital_letter_o |  latin_small_letter_closed_reversed_open_e
	Q ʢ		;]	 ⇔	 0051 |  02A2	 latin_capital_letter_q |  latin_letter_reversed_glottal_stop_with_stroke
	r ɽ		;]	 ⇔	 0072 |  027D	 latin_small_letter_r |  latin_small_letter_r_with_tail
	R ɻ		;]	 ⇔	 0052 |  027B	 latin_capital_letter_r |  latin_small_letter_turned_r_with_hook
	s ʂ		;]	 ⇔	 0073 |  0282	 latin_small_letter_s |  latin_small_letter_s_with_hook
	t ʈ		;]	 ⇔	 0074 |  0288	 latin_small_letter_t |  latin_small_letter_t_with_retroflex_hook
	u ʊ		;]	 ⇔	 0075 |  028A	 latin_small_letter_u |  latin_small_letter_upsilon
	v ⱱ		;]	 ⇔	 0076 |  2C71	 latin_small_letter_v |  <???>
	w ⱳ		;]	 ⇔	 0077 |  2C73	 latin_small_letter_w |  <???>
	y ɥ		;]	 ⇔	 0079 |  0265	 latin_small_letter_y |  latin_small_letter_turned_h
	z ʐ		;]	 ⇔	 007A |  0290	 latin_small_letter_z |  latin_small_letter_z_with_retroflex_hook
)
RegisterRota(7, rota, 0x3C, 0, 0x3C)	;|	less-than_sign (<)  less-than_sign (<)

; vertical bar ( | ) - - A general set of alternate forms
rota =
( C
	\	|	;]	 ↚	 005C |  007C	 reverse_solidus |  vertical_line
	A ᴀ		;]	 ⇔	 0041 |  1D00	 latin_capital_letter_a |  latin_letter_small_capital_a
	a α		;]	 ⇔	 0061 |  03B1	 latin_small_letter_a |  greek_small_letter_alpha
	d ȡ		;]	 ⇔	 0064 |  0221	 latin_small_letter_d |  latin_small_letter_d_with_curl
	E ᴇ		;]	 ⇔	 0045 |  1D07	 latin_capital_letter_e |  latin_letter_small_capital_e
	e ʚ		;]	 ⇔	 0065 |  029A	 latin_small_letter_e |  latin_small_letter_closed_open_e
	h ђ		;]	 ⇔	 0068 |  0452	 latin_small_letter_h |  cyrillic_small_letter_dje
	i ɩ		;]	 ⇔	 0069 |  0269	 latin_small_letter_i |  latin_small_letter_iota
	l ȴ		;]	 ⇔	 006C |  0234	 latin_small_letter_l |  latin_small_letter_l_with_curl
	n ȵ		;]	 ⇔	 006E |  0235	 latin_small_letter_n |  latin_small_letter_n_with_curl
	T ʇ		;]	 ⇔	 0054 |  0287	 latin_capital_letter_t |  latin_small_letter_turned_t
	t ȶ		;]	 ⇔	 0074 |  0236	 latin_small_letter_t |  latin_small_letter_t_with_curl
	u ɷ		;]	 ⇔	 0075 |  0277	 latin_small_letter_u |  latin_small_letter_closed_omega
	Y ʯ		;]	 ⇔	 0059 |  02AF	 latin_capital_letter_y |  latin_small_letter_turned_h_with_fishhook_and_tail
	y ʮ		;]	 ⇔	 0079 |  02AE	 latin_small_letter_y |  latin_small_letter_turned_h_with_fishhook
	Z ʅ		;]	 ⇔	 005A |  0285	 latin_capital_letter_z |  latin_small_letter_squat_reversed_esh
	z ɿ		;]	 ⇔	 007A |  027F	 latin_small_letter_z |  latin_small_letter_reversed_r_with_fishhook
)
RegisterRota(8, rota, 0x7C, 0, 0x7C)	;|	vertical_line (|)  vertical_line (|)

; Key: Circumflex ( ^ )  - For superscripting
rota =
( C
	\	^	;]	 ↚	 005C |  005E	 reverse_solidus |  circumflex_accent
	0 ⁰		;]	 ⇔	 0030 |  2070	 digit_zero |  superscript_zero
	1 ¹		;]	 ⇔	 0031 |  00B9	 digit_one |  superscript_one
	2 ²		;]	 ⇔	 0032 |  00B2	 digit_two |  superscript_two
	3 ³		;]	 ⇔	 0033 |  00B3	 digit_three |  superscript_three
	4 ⁴		;]	 ⇔	 0034 |  2074	 digit_four |  superscript_four
	5 ⁵		;]	 ⇔	 0035 |  2075	 digit_five |  superscript_five
	6 ⁶		;]	 ⇔	 0036 |  2076	 digit_six |  superscript_six
	7 ⁷		;]	 ⇔	 0037 |  2077	 digit_seven |  superscript_seven
	8 ⁸		;]	 ⇔	 0038 |  2078	 digit_eight |  superscript_eight
	9 ⁹		;]	 ⇔	 0039 |  2079	 digit_nine |  superscript_nine
	- ⁻		;]	 ⇔	 002D |  207B	 hyphen-minus |  superscript_minus
	+ ⁺		;]	 ⇔	 002B |  207A	 plus_sign |  superscript_plus_sign
	= ⁼		;]	 ⇔	 003D |  207C	 equals_sign |  superscript_equals_sign
	ʕ ˤ		;]	 ⇔	 0295 |  02E4	 latin_letter_pharyngeal_voiced_fricative |  modifier_letter_small_reversed_glottal_stop
	ʔ ˀ		;]	 ⇔	 0294 |  02C0	 latin_letter_glottal_stop |  modifier_letter_glottal_stop
	b ᵇ		;]	 ⇔	 0062 |  1D47	 latin_small_letter_b |  modifier_letter_small_b
	β ᵝ		;]	 ⇔	 03B2 |  1D5D	 greek_small_letter_beta |  modifier_letter_small_beta
	c ᶜ		;]	 ⇔	 0063 |  1D9C	 latin_small_letter_c |  modifier_letter_small_c
	ɕ ᶝ		;]	 ⇔	 0255 |  1D9D	 latin_small_letter_c_with_curl |  modifier_letter_small_c_with_curl
	d ᵈ		;]	 ⇔	 0064 |  1D48	 latin_small_letter_d |  modifier_letter_small_d
	ð ᶞ		;]	 ⇔	 00F0 |  1D9E	 latin_small_letter_eth |  modifier_letter_small_eth
	f ᶠ
;]	 ⇔	 0066 |  1DA0	 latin_small_letter_f |  modifier_letter_small_f	(No comments permitted on same line following ᶠ)
	g ᵍ		;]	 ⇔	 0067 |  1D4D	 latin_small_letter_g |  modifier_letter_small_g
	ɡ ᶢ		;]	 ⇔	 0261 |  1DA2	 latin_small_letter_script_g |  modifier_letter_small_script_g
	ɣ ˠ
;]	 ⇔	 0263 |  02E0	 latin_small_letter_gamma |  modifier_letter_small_gamma	(No comments permitted on same line following ˠ)
	h ʰ		;]	 ⇔	 0068 |  02B0	 latin_small_letter_h |  modifier_letter_small_h
	ɦ ʱ		;]	 ⇔	 0266 |  02B1	 latin_small_letter_h_with_hook |  modifier_letter_small_h_with_hook
	ɥ ᶣ		;]	 ⇔	 0265 |  1DA3	 latin_small_letter_turned_h |  modifier_letter_small_turned_h
	ħ 		;]	 ⇔	 0127 |  F1BC	 latin_small_letter_h_with_stroke |  <private>
	j ʲ		;]	 ⇔	 006A |  02B2	 latin_small_letter_j |  modifier_letter_small_j
	ʝ ᶨ		;]	 ⇔	 029D |  1DA8	 latin_small_letter_j_with_crossed-tail |  modifier_letter_small_j_with_crossed-tail
	ɟ ᶡ		;]	 ⇔	 025F |  1DA1	 latin_small_letter_dotless_j_with_stroke |  modifier_letter_small_dotless_j_with_stroke
	k ᵏ		;]	 ⇔	 006B |  1D4F	 latin_small_letter_k |  modifier_letter_small_k
	l ˡ		;]	 ⇔	 006C |  02E1	 latin_small_letter_l |  modifier_letter_small_l
	ɭ ᶩ		;]	 ⇔	 026D |  1DA9	 latin_small_letter_l_with_retroflex_hook |  modifier_letter_small_l_with_retroflex_hook
	ʟ ᶫ		;]	 ⇔	 029F |  1DAB	 latin_letter_small_capital_l |  modifier_letter_small_capital_l
	m ᵐ		;]	 ⇔	 006D |  1D50	 latin_small_letter_m |  modifier_letter_small_m
	ɱ ᶬ		;]	 ⇔	 0271 |  1DAC	 latin_small_letter_m_with_hook |  modifier_letter_small_m_with_hook
	n ⁿ		;]	 ⇔	 006E |  207F	 latin_small_letter_n |  superscript_latin_small_letter_n
	ɲ ᶮ		;]	 ⇔	 0272 |  1DAE	 latin_small_letter_n_with_left_hook |  modifier_letter_small_n_with_left_hook
	ŋ ᵑ		;]	 ⇔	 014B |  1D51	 latin_small_letter_eng |  modifier_letter_small_eng
	ɳ ᶯ		;]	 ⇔	 0273 |  1DAF	 latin_small_letter_n_with_retroflex_hook |  modifier_letter_small_n_with_retroflex_hook
	ɴ ᶰ		;]	 ⇔	 0274 |  1DB0	 latin_letter_small_capital_n |  modifier_letter_small_capital_n
	p ᵖ		;]	 ⇔	 0070 |  1D56	 latin_small_letter_p |  modifier_letter_small_p
	ɸ ᶲ		;]	 ⇔	 0278 |  1DB2	 latin_small_letter_phi |  modifier_letter_small_phi
	r ʳ		;]	 ⇔	 0072 |  02B3	 latin_small_letter_r |  modifier_letter_small_r
	ɹ ʴ		;]	 ⇔	 0279 |  02B4	 latin_small_letter_turned_r |  modifier_letter_small_turned_r
	ɻ ʵ		;]	 ⇔	 027B |  02B5	 latin_small_letter_turned_r_with_hook |  modifier_letter_small_turned_r_with_hook
	ʁ ʶ		;]	 ⇔	 0281 |  02B6	 latin_letter_small_capital_inverted_r |  modifier_letter_small_capital_inverted_r
	s ˢ		;]	 ⇔	 0073 |  02E2	 latin_small_letter_s |  modifier_letter_small_s
	ʂ ᶳ		;]	 ⇔	 0282 |  1DB3	 latin_small_letter_s_with_hook |  modifier_letter_small_s_with_hook
	ʃ ᶴ		;]	 ⇔	 0283 |  1DB4	 latin_small_letter_esh |  modifier_letter_small_esh
	t ᵗ		;]	 ⇔	 0074 |  1D57	 latin_small_letter_t |  modifier_letter_small_t
	ɰ ᶭ		;]	 ⇔	 0270 |  1DAD	 latin_small_letter_turned_m_with_long_leg |  modifier_letter_small_turned_m_with_long_leg
	v ᵛ		;]	 ⇔	 0076 |  1D5B	 latin_small_letter_v |  modifier_letter_small_v
	ʋ ᶹ		;]	 ⇔	 028B |  1DB9	 latin_small_letter_v_with_hook |  modifier_letter_small_v_with_hook
	w ʷ		;]	 ⇔	 0077 |  02B7	 latin_small_letter_w |  modifier_letter_small_w
	x ˣ		;]	 ⇔	 0078 |  02E3	 latin_small_letter_x |  modifier_letter_small_x
	z ᶻ		;]	 ⇔	 007A |  1DBB	 latin_small_letter_z |  modifier_letter_small_z
	ʑ ᶽ		;]	 ⇔	 0291 |  1DBD	 latin_small_letter_z_with_curl |  modifier_letter_small_z_with_curl
	ʐ ᶼ		;]	 ⇔	 0290 |  1DBC	 latin_small_letter_z_with_retroflex_hook |  modifier_letter_small_z_with_retroflex_hook
	ʒ ᶾ		;]	 ⇔	 0292 |  1DBE	 latin_small_letter_ezh |  modifier_letter_small_ezh
	θ ᶿ		;]	 ⇔	 03B8 |  1DBF	 greek_small_letter_theta |  modifier_letter_small_theta
	ʎ 		;]	 ⇔	 028E |  F1CE	 latin_small_letter_turned_y |  <private>
	a ᵃ		;]	 ⇔	 0061 |  1D43	 latin_small_letter_a |  modifier_letter_small_a
	ɐ ᵄ		;]	 ⇔	 0250 |  1D44	 latin_small_letter_turned_a |  modifier_letter_small_turned_a
	ɑ ᵅ		;]	 ⇔	 0251 |  1D45	 latin_small_letter_alpha |  modifier_letter_small_alpha
	ɒ ᶛ		;]	 ⇔	 0252 |  1D9B	 latin_small_letter_turned_alpha |  modifier_letter_small_turned_alpha
	æ 		;]	 ⇔	 00E6 |  F1A1	 latin_small_letter_ae |  <private>
	ᴂ ᵆ		;]	 ⇔	 1D02 |  1D46	 latin_small_letter_turned_ae |  modifier_letter_small_turned_ae
	e ᵉ		;]	 ⇔	 0065 |  1D49	 latin_small_letter_e |  modifier_letter_small_e
	ə ᵊ		;]	 ⇔	 0259 |  1D4A	 latin_small_letter_schwa |  modifier_letter_small_schwa
	ɛ ᵋ		;]	 ⇔	 025B |  1D4B	 latin_small_letter_open_e |  modifier_letter_small_open_e
	ɜ ᶟ		;]	 ⇔	 025C |  1D9F	 latin_small_letter_reversed_open_e |  modifier_letter_small_reversed_open_e
	ɘ 		;]	 ⇔	 0258 |  F1A3	 latin_small_letter_reversed_e |  <private>
	i ⁱ		;]	 ⇔	 0069 |  2071	 latin_small_letter_i |  superscript_latin_small_letter_i
	ɨ ᶤ		;]	 ⇔	 0268 |  1DA4	 latin_small_letter_i_with_stroke |  modifier_letter_small_i_with_stroke
	ɪ ᶦ		;]	 ⇔	 026A |  1DA6	 latin_letter_small_capital_i |  modifier_letter_small_capital_i
	o ᵒ		;]	 ⇔	 006F |  1D52	 latin_small_letter_o |  modifier_letter_small_o
	ø 		;]	 ⇔	 00F8 |  F1AB	 latin_small_letter_o_with_stroke |  <private>
	œ 		;]	 ⇔	 0153 |  F1AD	 latin_small_ligature_oe |  <private>
	ɶ 		;]	 ⇔	 0276 |  F1AE	 latin_letter_small_capital_oe |  <private>
	ɵ ᶱ		;]	 ⇔	 0275 |  1DB1	 latin_small_letter_barred_o |  modifier_letter_small_barred_o
	ɔ ᵓ		;]	 ⇔	 0254 |  1D53	 latin_small_letter_open_o |  modifier_letter_small_open_o
	u ᵘ		;]	 ⇔	 0075 |  1D58	 latin_small_letter_u |  modifier_letter_small_u
	ʉ ᶶ		;]	 ⇔	 0289 |  1DB6	 latin_small_letter_u_bar |  modifier_letter_small_u_bar
	y ʸ		;]	 ⇔	 0079 |  02B8	 latin_small_letter_y |  modifier_letter_small_y
	ʏ 		;]	 ⇔	 028F |  F1B4	 latin_letter_small_capital_y |  <private>
	ɯ ᵚ		;]	 ⇔	 026F |  1D5A	 latin_small_letter_turned_m |  modifier_letter_small_turned_m
	ɤ 		;]	 ⇔	 0264 |  F1B5	 latin_small_letter_rams_horn |  <private>
	ɞ 		;]	 ⇔	 025E |  F1A4	 latin_small_letter_closed_reversed_open_e |  <private>
	ʌ ᶺ		;]	 ⇔	 028C |  1DBA	 latin_small_letter_turned_v |  modifier_letter_small_turned_v
	ʊ ᶷ		;]	 ⇔	 028A |  1DB7	 latin_small_letter_upsilon |  modifier_letter_small_upsilon
)
; because we can't use parentheses inside a continuation section:
rota = %rota%`n( ⁽`n) ⁾	 ;  0x207D and 0x207E	;|	superscript_left_parenthesis (⁽)  superscript_right_parenthesis (⁾)
RegisterRota(9, rota, 0x5e, 0, 0x5e)	;|	circumflex_accent (^)  circumflex_accent (^)

; tilde ( ~ )  - This is a non-looping rota, to match IPAUni12.kmn functionality (probably unneccesarily closely)
RegisterRota(10, "\ ~	b̃ ᵬ	d̃ ᵭ	f̃ ᵮ	l̃ ɫ	m̃ ᵯ	ñ ᵰ	p̃ ᵱ	r̃ ᵲ	ɾ̃ ᵳ	s̃ ᵴ	t̃ ᵵ	z̃ ᵶ"
;|	\ ~		 005C |  007E		 reverse_solidus |  tilde
;|	b◌̃ ᵬ		 0062 0303 |  1D6C		 latin_small_letter_b combining_tilde |  latin_small_letter_b_with_middle_tilde
;|	d◌̃ ᵭ		 0064 0303 |  1D6D		 latin_small_letter_d combining_tilde |  latin_small_letter_d_with_middle_tilde
;|	f◌̃ ᵮ		 0066 0303 |  1D6E		 latin_small_letter_f combining_tilde |  latin_small_letter_f_with_middle_tilde
;|	l◌̃ ɫ		 006C 0303 |  026B		 latin_small_letter_l combining_tilde |  latin_small_letter_l_with_middle_tilde
;|	m◌̃ ᵯ		 006D 0303 |  1D6F		 latin_small_letter_m combining_tilde |  latin_small_letter_m_with_middle_tilde
;|	n◌̃ ᵰ		 006E 0303 |  1D70		 latin_small_letter_n combining_tilde |  latin_small_letter_n_with_middle_tilde
;|	p◌̃ ᵱ		 0070 0303 |  1D71		 latin_small_letter_p combining_tilde |  latin_small_letter_p_with_middle_tilde
;|	r◌̃ ᵲ		 0072 0303 |  1D72		 latin_small_letter_r combining_tilde |  latin_small_letter_r_with_middle_tilde
;|	ɾ◌̃ ᵳ		 027E 0303 |  1D73		 latin_small_letter_r_with_fishhook combining_tilde |  latin_small_letter_r_with_fishhook_and_middle_tilde
;|	s◌̃ ᵴ		 0073 0303 |  1D74		 latin_small_letter_s combining_tilde |  latin_small_letter_s_with_middle_tilde
;|	t◌̃ ᵵ		 0074 0303 |  1D75		 latin_small_letter_t combining_tilde |  latin_small_letter_t_with_middle_tilde
;|	z◌̃ ᵶ		 007A 0303 |  1D76		 latin_small_letter_z combining_tilde |  latin_small_letter_z_with_middle_tilde
			, 0x303, 0, 0x7E, 3)	;|	combining_tilde (◌̃)  tilde (~)

; Key: Ampersand ( & )  - For tying ties or for combining/splitting affricates.
rota =
( C
	\	&	;]	 ↚	 005C |  0026	 reverse_solidus |  ampersand
	# ͡		;]	 ⇔	 0023 |  0361	 number_sign |  combining_double_inverted_breve
	̊ ͜		;]	 ⇔	 030A |  035C	 combining_ring_above |  combining_double_breve_below
	dz ʣ		;]	 ⇔	 0064 007A |  02A3	 latin_small_letter_d latin_small_letter_z |  latin_small_letter_dz_digraph
	dʒ ʤ		;]	 ⇔	 0064 0292 |  02A4	 latin_small_letter_d latin_small_letter_ezh |  latin_small_letter_dezh_digraph
	dʑ ʥ		;]	 ⇔	 0064 0291 |  02A5	 latin_small_letter_d latin_small_letter_z_with_curl |  latin_small_letter_dz_digraph_with_curl
	ts ʦ		;]	 ⇔	 0074 0073 |  02A6	 latin_small_letter_t latin_small_letter_s |  latin_small_letter_ts_digraph
	tʃ ʧ		;]	 ⇔	 0074 0283 |  02A7	 latin_small_letter_t latin_small_letter_esh |  latin_small_letter_tesh_digraph
	tɕ ʨ		;]	 ⇔	 0074 0255 |  02A8	 latin_small_letter_t latin_small_letter_c_with_curl |  latin_small_letter_tc_digraph_with_curl
	fŋ ʩ 		;]	 ⇔	 0066 014B |  02A9	 latin_small_letter_f latin_small_letter_eng |  latin_small_letter_feng_digraph
	ls ʪ		;]	 ⇔	 006C 0073 |  02AA	 latin_small_letter_l latin_small_letter_s |  latin_small_letter_ls_digraph
	lz ʫ		;]	 ⇔	 006C 007A |  02AB	 latin_small_letter_l latin_small_letter_z |  latin_small_letter_lz_digraph
	lʒ ɮ		;]	 ⇔	 006C 0292 |  026E	 latin_small_letter_l latin_small_letter_ezh |  latin_small_letter_lezh
)
RegisterRota(11, rota, 0x26, 0)		;|	ampersand (&)

; Key: left curly bracket ( { ) - For Dental/Apical/Laminal/Lingulabial/Fricative
RegisterRota(12, "̪ ̺ ̻ ̼ ̣"
;|	◌̪ ◌̺ ◌̻ ◌̼ ◌̣		 032A |  033A |  033B |  033C |  0323		 combining_bridge_below |  combining_inverted_bridge_below |  combining_square_below |  combining_seagull_below |  combining_dot_below
			, 0x32A, 0, 0x7B)	;|	combining_bridge_below (◌̪)  left_curly_bracket ({)

; Key: right curly bracket ( } )  - For stress / fortis-lenis
rota =
( C
	\	}
	ˈ ˌ ͈ ᷂ }
)
RegisterRota(13, rota, 0x2C8, 0, 0x7D)	;|	modifier_letter_vertical_line (ˈ)  right_curly_bracket (})

; Key: right square bracket
RegisterRota(14, "] ʼ ̚ ʻ"
;|	] ʼ ◌̚ ʻ		 005D |  02BC |  031A |  02BB		 right_square_bracket |  modifier_letter_apostrophe |  combining_left_angle_above |  modifier_letter_turned_comma
			, 0x5D, 0, 0, 2)	;|	right_square_bracket (])

; Key: left square bracket
RegisterRota(15, "[ ʽ ˞"
;|	[ ʽ ˞		 005B |  02BD |  02DE		 left_square_bracket |  modifier_letter_reversed_comma |  modifier_letter_rhotic_hook
			, 0x5B, 0, 0, 2)	;|	left_square_bracket ([)

; Key: asterisk ( * )
RegisterRota(16, "̈ ̽ ̆ ̇ ̐"
;|	◌̈ ◌̽ ◌̆ ◌̇ ◌̐		 0308 |  033D |  0306 |  0307 |  0310		 combining_diaeresis |  combining_x_above |  combining_breve |  combining_dot_above |  combining_candrabindu
			, 0x308, 0, 0x2A)		;|	combining_diaeresis (◌̈)  asterisk (*)

; plus sign ( + )
RegisterRota(17, "̟ ̝ ̘ ̹"	; advanced / raised / +ATR / more rounded
;|	◌̟ ◌̝ ◌̘ ◌̹		 031F |  031D |  0318 |  0339		 combining_plus_sign_below |  combining_up_tack_below |  combining_left_tack_below |  combining_right_half_ring_below
			, 0x31F, 0, 0x2B)		;|	combining_plus_sign_below (◌̟)  plus_sign (+)

; underscore ( _ )
RegisterRota(18, "̠ ̞ ̙ ̜ ̧"	; retracted / lowered / -ATR / less rounded / open vowel
;|	◌̠ ◌̞ ◌̙ ◌̜ ◌̧		 0320 |  031E |  0319 |  031C |  0327		 combining_minus_sign_below |  combining_down_tack_below |  combining_right_tack_below |  combining_left_half_ring_below |  combining_cedilla
			, 0x320, 0, 0x5F)		;|	combining_minus_sign_below (◌̠)  low_line (_)

; percent (%) for lower diacritics
RegisterRota(20, "̥ ̬ ̤"
;|	◌̥ ◌̬ ◌̤		 0325 |  032C |  0324		 combining_ring_below |  combining_caron_below |  combining_diaeresis_below
			, 0x325, 0, 0x25)		;|	combining_ring_below (◌̥)  percent_sign (%)

; percent (%) for palatal hooks	(This is a non-looping rota.)
RegisterRota(19, "b̤ ᶀ	d̤ ᶁ	f̤ ᶂ	g̤ ᶃ	k̤ ᶄ	l̤ ᶅ	m̤ ᶆ	n̤ ᶇ	p̤ ᶈ	r̤ ᶉ	s̤ ᶊ	ʃ̤ ᶋ	v̤ ᶌ	x̤ ᶍ	z̤ ᶎ"
;|	b◌̤ ᶀ		 0062 0324 |  1D80		 latin_small_letter_b combining_diaeresis_below |  latin_small_letter_b_with_palatal_hook
;|	d◌̤ ᶁ		 0064 0324 |  1D81		 latin_small_letter_d combining_diaeresis_below |  latin_small_letter_d_with_palatal_hook
;|	f◌̤ ᶂ		 0066 0324 |  1D82		 latin_small_letter_f combining_diaeresis_below |  latin_small_letter_f_with_palatal_hook
;|	g◌̤ ᶃ		 0067 0324 |  1D83		 latin_small_letter_g combining_diaeresis_below |  latin_small_letter_g_with_palatal_hook
;|	k◌̤ ᶄ		 006B 0324 |  1D84		 latin_small_letter_k combining_diaeresis_below |  latin_small_letter_k_with_palatal_hook
;|	l◌̤ ᶅ		 006C 0324 |  1D85		 latin_small_letter_l combining_diaeresis_below |  latin_small_letter_l_with_palatal_hook
;|	m◌̤ ᶆ		 006D 0324 |  1D86		 latin_small_letter_m combining_diaeresis_below |  latin_small_letter_m_with_palatal_hook
;|	n◌̤ ᶇ		 006E 0324 |  1D87		 latin_small_letter_n combining_diaeresis_below |  latin_small_letter_n_with_palatal_hook
;|	p◌̤ ᶈ		 0070 0324 |  1D88		 latin_small_letter_p combining_diaeresis_below |  latin_small_letter_p_with_palatal_hook
;|	r◌̤ ᶉ		 0072 0324 |  1D89		 latin_small_letter_r combining_diaeresis_below |  latin_small_letter_r_with_palatal_hook
;|	s◌̤ ᶊ		 0073 0324 |  1D8A		 latin_small_letter_s combining_diaeresis_below |  latin_small_letter_s_with_palatal_hook
;|	ʃ◌̤ ᶋ		 0283 0324 |  1D8B		 latin_small_letter_esh combining_diaeresis_below |  latin_small_letter_esh_with_palatal_hook
;|	v◌̤ ᶌ		 0076 0324 |  1D8C		 latin_small_letter_v combining_diaeresis_below |  latin_small_letter_v_with_palatal_hook
;|	x◌̤ ᶍ		 0078 0324 |  1D8D		 latin_small_letter_x combining_diaeresis_below |  latin_small_letter_x_with_palatal_hook
;|	z◌̤ ᶎ		 007A 0324 |  1D8E		 latin_small_letter_z combining_diaeresis_below |  latin_small_letter_z_with_palatal_hook
			, 0, 0, 0x25, 3)  ;|	percent_sign (%)

; Key: dollar sign ( $ )
RegisterRota(22, "̩ ̯ ̰"	; syllabic / non-syllabic / creaky-voiced
;|	◌̩ ◌̯ ◌̰		 0329 |  032F |  0330		 combining_vertical_line_below |  combining_inverted_breve_below |  combining_tilde_below
			, 0x329, 0, 0x24)	;|	combining_vertical_line_below (◌̩)  dollar_sign ($)
;...
RegisterRota(21, "a̰ ᶏ	ɑ̰ ᶐ	ɗ̰ ᶑ	ḛ ᶒ	ɛ̰ ᶓ	ɜ̰ ᶔ	ə̰ ᶕ	ḭ ᶖ	ɔ̰ ᶗ	ʃ̰ ᶘ	ṵ ᶙ	ʒ̰ ᶚ"
;|	a◌̰ ᶏ		 0061 0330 |  1D8F		 latin_small_letter_a combining_tilde_below |  latin_small_letter_a_with_retroflex_hook
;|	ɑ◌̰ ᶐ		 0251 0330 |  1D90		 latin_small_letter_alpha combining_tilde_below |  latin_small_letter_alpha_with_retroflex_hook
;|	ɗ◌̰ ᶑ		 0257 0330 |  1D91		 latin_small_letter_d_with_hook combining_tilde_below |  latin_small_letter_d_with_hook_and_tail
;|	e◌̰ ᶒ		 0065 0330 |  1D92		 latin_small_letter_e combining_tilde_below |  latin_small_letter_e_with_retroflex_hook
;|	ɛ◌̰ ᶓ		 025B 0330 |  1D93		 latin_small_letter_open_e combining_tilde_below |  latin_small_letter_open_e_with_retroflex_hook
;|	ɜ◌̰ ᶔ		 025C 0330 |  1D94		 latin_small_letter_reversed_open_e combining_tilde_below |  latin_small_letter_reversed_open_e_with_retroflex_hook
;|	ə◌̰ ᶕ		 0259 0330 |  1D95		 latin_small_letter_schwa combining_tilde_below |  latin_small_letter_schwa_with_retroflex_hook
;|	i◌̰ ᶖ		 0069 0330 |  1D96		 latin_small_letter_i combining_tilde_below |  latin_small_letter_i_with_retroflex_hook
;|	ɔ◌̰ ᶗ		 0254 0330 |  1D97		 latin_small_letter_open_o combining_tilde_below |  latin_small_letter_open_o_with_retroflex_hook
;|	ʃ◌̰ ᶘ		 0283 0330 |  1D98		 latin_small_letter_esh combining_tilde_below |  latin_small_letter_esh_with_retroflex_hook
;|	u◌̰ ᶙ		 0075 0330 |  1D99		 latin_small_letter_u combining_tilde_below |  latin_small_letter_u_with_retroflex_hook
;|	ʒ◌̰ ᶚ		 0292 0330 |  1D9A		 latin_small_letter_ezh combining_tilde_below |  latin_small_letter_ezh_with_retroflex_hook
			, 0, 0, 0x24, 3)  ; This is a non-looping rota. ;|	dollar_sign ($)

; Key: Colon ( : )
rota =
( C
	\	:	;]	 ↚	 005C |  003A	 reverse_solidus |  colon
	ːː ː ˑ		;]	 ⇔	 02D0 02D0 |  02D0 |  02D1	 modifier_letter_triangular_colon modifier_letter_triangular_colon |  modifier_letter_triangular_colon |  modifier_letter_half_triangular_colon
)
RegisterRota(23, rota, 0x02D0, 0, 0x3A)	;|	modifier_letter_triangular_colon (ː)  colon (:)

Return
;*   END OnLoadScript Subroutine

;----------------------------------------------------------------------------------------------
; IPA Functions

DoLevelContour(dd) {	; Begin or continue a level pitch contour sequence.
	global cc
	if ((cc >= 0xF1F1 and cc <= 0xF1F9)) ;|	<private> ()  <private> ()
		SendChar(0xF1F0 + dd)	; level pitch contour
	else if ((cc = 0x23) and (ctx(2) = 0x23))	; after ##	;|	number_sign (#)  number_sign (#)
		ReplaceChar(0xF1F0 + dd, 2)
	else
		return 0
	return 1
}

DoStemTone(dd) {	; For continuation of a right or left stem tone contour.
	global cc		; (Initial stem tone is generated by the DoRota function.)
	if ((cc >= 0x2E5 and cc <= 0x2E9)) 	;|	modifier_letter_extra-high_tone_bar (˥)  modifier_letter_extra-low_tone_bar (˩)
		SendChar(0x02E9 - dd)		; left stem
	else if ((cc >= 0xA712 and cc <= 0xA716)) ;|	modifier_letter_extra-high_left-stem_tone_bar (꜒)  modifier_letter_extra-low_left-stem_tone_bar (꜖)
		SendChar(0xA712 + dd)		; right stem
	else
		return 0
	return 1
}

DoDiacriticRota(rota, key) {
; This function prevents the rota from performing a substitution when the key follows a lower-ANSI (i.e < 0x7F) non-letter character.
; Useful for typing underscore (e.g. m → n / __ k)  or plus ( e.g. [+voiced] ) without these being replaced with diacritics.
; Furthermore, the rota substitution can be explicitly prevented in any context by typing a backslash (\) before the key.
	cc := ctx()
	if (cc = 0x5C)		; If after a backslash (\),
		ReplaceChar(key) 	;   replace the backslash with the key's own character.
	else if (cc > 0x7F or (cc >= 0x61 and cc <= 0x7A) or (cc >= 0x41 and cc <= 0x5A) )
		return DoRota(rota)	;  If not lower-ANSI, or if in [A-Z] or [a-z], do the specified rota.
	else
		SendChar(key)		; Otherwise, send the key itself.
	return 1
}

;----------------------------------------------------------------------------------------------
; IPA Function Keys:

; The digits have the most complex usage pattern, used for level contours, stem tones, rotas, and the digits themselves.

$0::				; Key: Zero
cc := ctx()	; Call ctx() once and assign it to a global variable for efficiency
DoStemTone(0) or DoRota(0)
return

$1::				; Keys: 1-4
$2::
$3::
$4::
dd := SubStr(A_ThisHotKey,0)  ; i.e. remove the $ to get just the digit
cc := ctx()
DoLevelContour(dd) or DoStemTone(dd) or DoRota(dd)
return

$5::				; Keys: 5-9
$6::
$7::
$8::
$9::
dd := SubStr(A_ThisHotKey,0)  ; i.e. remove the $ to get just the digit
cc := ctx()
DoLevelContour(dd) or SendChar(Asc(dd))
return

; The non-digits are more straightforward:

$=::DoRota(5)    		; Key: Equal Sign (=)
$>::DoRota(6)		; Key:  Right wedge (>)
$<::DoRota(7)		; Key:  Left Wedge (<)
$|::DoRota(8)		; Key: Vertical line ( | )
$^::DoRota(9)		; Key: Circumflex (^)
$~::DoRota(10)		; Key: Tilde ( ~ )
$&::DoRota(11)		; Key: Ampersand ( & )
${::DoDiacriticRota(12, 0x7B)		; Key:  Left curly bracket ( { ) - For Dental/Apical/Laminal/Lingulabial/Fricative diacritics
$}::DoRota(13)		; Key: Right Curly bracket ( } ) - For stress / fortis-lenis.  May be word initial; Not a diacritic.
$]::DoRota(14)		; Key: right_square_bracket	( ] ) - By default puts own key out first.
$[::DoRota(15)		; Key: left square_bracket	( [ ) - By default puts own key out first.
$*::DoDiacriticRota(16, 0x2A)		; Key: asterisk ( * )
$+::DoDiacriticRota(17, 0x2B)	; Key: plus ( + )
$_::DoDiacriticRota(18, 0x5F)	; Key: Underscore (_)    ;|	low_line (_)
$%::DoRota(19) or DoDiacriticRota(20, 0x25) ; Key: (%) for palatal hook characters  or lower diacritics
$$::DoRota(21) or DoDiacriticRota(22, 0x24) ; Key: ($) for retroflex hook characters  or syllabic / non-syllabic / creaky-voiced
$+;::DoRota(23)		; Key: colon ( : )

$!::						; Key: exclamation point
if (ctx() = 0x5C)		;|	reverse_solidus (\)
	ReplaceChar(0x21)	;|	exclamation_mark (!)
else
	SendChar(0x01C3)	;|	latin_letter_retroflex_click (ǃ)
return

$@::						; Key: AT symbol ( @ )
cc := ctx()
if (cc = 0x5C)		;|	reverse_solidus (\)
	ReplaceChar(0x40)	;|	commercial_at (@)
else if (cc = 0x030A)		;|	combining_ring_above (◌̊)
	ReplaceChar(0x40)	;|	commercial_at (@)
else
	SendChar(0x030A)	;|	combining_ring_above (◌̊)
return
